### ISSUE TITLE
[testing-karma] switch to karma-coverage

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1164]
We are using `karma-coverage-istanbul-reporter`, but it's using an outdated istanbul API and doesn't accept community feature requests / contributions unless you are a donator. [karma-coverage](https://github.com/karma-runner/karma-coverage) seems to be a good replacement.

**Comment by Westbrook** [comment]
Do you think we'd try to manage the change in config objects under the covers or would this just be an outright breaking change?  E.G.:

```
coverageIstanbulReporter: {
  thresholds: {
    global: {
      statements: 95,
      branches: 86,
      functions: 97,
      lines: 96,
    },
  },
},
```

Becomes:

```
coverageReporter: {
  check: {
    global: {
      statements: 95,
      branches: 86,
      functions: 97,
      lines: 96,
    }
  }
}
```

**Comment by LarsDenBakker** [comment]
Good point, we may be able to but it's likely that not all options will map over properly. So we'd need to weigh some pros and cons to decide whether it's worth a breaking change.

**Comment by benjamind** [comment]
I just wasted an afternoon trying to get our html coverage reports to work again after installing latest versions of everything today... here's the pain I just uncovered due to this dependency on `karma-coverage-istanbul-reporter`

`karma-esm` is using `babel-plugin-istanbul` to instrument the code served by `es-dev-server` using istanbul and produce the coverage data. `@open-wc/testing-karma` then itself uses the `karma-coverage-istanbul-reporter` to take the instrumented code and output a coverage report. This all seems reasonable at first glance.

Unfortunately `karma-coverage-istanbul-reporter` is a bit of a dead project, and depends upon istanbul-api which itself is a deprecated package. This is made more unfortunate by a security bug in `handlebars` which the `2.x` version of the `istanbul-reporters` package uses to render its templates. handlebars did a [minor package update to 'fix' their security bug](https://github.com/wycats/handlebars.js/blob/master/release-notes.md#v460---january-8th-2020), but in the process broke the `istanbul-reports` template rendering for their html reporter.

`istanbul` have of course fixed all this by now, and have gone up a major version to 3.x, like good citizens, and switched away from handlebars for their templates. But because `karma-coverage-istanbul-reporter` is basically a dead project it has not made the update to use the `3.x` versions of istanbuls packages. `karma-coverage-istanbul-reporter` is automatically [closing tickets and PR with a bot unless filed by a patreon supporter](https://github.com/mattlewis92/karma-coverage-istanbul-reporter/issues/78#issuecomment-555244951)). So the coverage reports are basically broken because of this minor dependency mismatch, you have the option of running unsafe security versions of handlebars (and manually forcing a lock onto an old handlebars version), or it not working at all.

So....plus one hundred for moving to `karma-coverage` asap please!

**Comment by coreyfarrell** [comment]
FYI I - just got a notification from karma-coverage that they have released to npm an update which uses all the latest Istanbul libraries.  I do not maintain or even use any karma libs but I do maintain the Istanbul libraries.  From a maintenance standpoint I'd recommend karma-coverage unless open-wc wants to fork karma-coverage-istanbul-reporter.

**Comment by web-padawan** [comment]
Here is the new release: https://github.com/karma-runner/karma-coverage/releases/tag/v2.0.2
