### ISSUE TITLE
Promise Polyfill finally not there in IE11/EDGE using open-wc/building

### ISSUE THREAD

**Issue by lakshay35** [open-wc/open-wc#1193]
I am getting errors in my web component when running in IE/EDGE when the finally block for a promise runs. I thought core-js included that but am not sure anymore. I have the latest version of core js installed. 

Note: I'm using es-dev-server in compatibility mode.

**Comment by LarsDenBakker** [comment]
We load the core-js polyfills only on IE11 due to the large size, so promise finally should work there. This means we miss out on some features like promise finally and array flat on browsers that do support modules but don't implement them. But they're not worth loading 150kb (non-gzip) polyfills in my opinion. We haven't figured out a good more fine grained polyfill loading strategy for this yet.

You could include the polyfills yourself on the page if you want though.
