### ISSUE TITLE
[es-dev-server] concatening twice the CWD and cannot find the configuration file.

### ISSUE THREAD

**Issue by vdegenne** [open-wc/open-wc#1195]
### Issue

I have a `es-dev-server.config.js` in the directory where I execute `es-dev-server`.
The configuration file is ignored.

This is what I get when using the `--debug` option

![image](https://user-images.githubusercontent.com/2827383/71767410-562b1b00-2f0c-11ea-92b3-b07db6ad75b6.png)

*Given the current working directory is `/root/gits/hanja-everlast` in this case the path is twice concatenated when trying to resolve the configuration file.*

### Versions

**os :** Debian 9 (stretch)
**es-dev-server :**  1.35.0

### Additional informations

- If I use `-c es-dev-server.config.js` directly, it works.
- I don't have this issue on my development machine (Fedora 31) although I have the same `es-dev-server`, `node` and `npm` version installed.

**Comment by rodrigo-garcia-leon** [comment]
I'm running into the same issue as well. I created a small repo to demo the issue: https://github.com/rodrigo-garcia-leon/es-dev-server-default-config-issue

In the repo, running `npm start` results in nothing, whereas running `npm start:config` opens the `index.html` file in a browser. This last behavior is the one expected in this case, since the config file has the `open` option in it.

Going into the code, in the file `packages/es-dev-server/src/command-line-args.js` I see the following (lines 215-220):

```js
    const defaultConfigPath = path.join(
      process.cwd(),
      dashesArgs['root-dir'] || '',
      defaultConfigDir,
      defaultConfigName,
    );
```

Like @vdegenne mentions, the CWD is being concatenated twice, because earlier in the code the variable `defaultConfigDir` is populated by a call to `process.cwd()` (line 163).

I guess this could be solved by doing something like this instead:

```js
    const defaultConfigPath = path.join(
      defaultConfigDir,
      dashesArgs['root-dir'] || '',
      defaultConfigName,
    );
```

So CWD only comes from `defaultConfigDir`, and the option `root-dir` is used for subsequent traversal if specified by the user.

**Comment by vdegenne** [comment]
Oddly on my fedora I run now into the same issue as well. I need to use `-c <config-filename>` explicitly.

**Comment by LarsDenBakker** [comment]
Thanks for reporting this guys
