### ISSUE TITLE
[eslint-config] Support optional chaining

### ISSUE THREAD

**Issue by doplumi** [open-wc/open-wc#1223]
As of right now, eslint erroneously shows a `no-unused-expression` error on optional chaining function calls / field access.

In `eslint-config/index.js` there's this rule:

```
  overrides: [
    {
      files: ['**/test/**/*.js', '**/demo/**/*.js', '**/stories/**/*.js'],
      rules: {
        'no-console': 'off',
        'no-unused-expressions': 'off',
        'class-methods-use-this': 'off',
      },
    },
  ],
```

Why was `no-unused-expressions` disabled for those cases? I'm trying to evaluate the best workaround to support optional chaining. Right now the best option seems to be https://github.com/eslint/eslint/issues/11045#issuecomment-436685184 but it would add a dependency on `eslint-plugin-babel`

**Comment by doplumi** [comment]
Just realized `babel-parser` already depends on `eslint-babel-plugin`, so that particular fix would be a 2 line change. Shall we go with it?

**Comment by LarsDenBakker** [comment]
Babel is about to release optional chaining support by default, I wonder if we get this out of the box then?

**Comment by tmsns** [comment]
Unfortunately, we will not get this out of the box, until eslint supports this by default. As mentioned by @doplumi, we can use/add babel's eslint plugin (`eslint-plugin-babel`). The idea would be to use their [specific rule](https://github.com/babel/eslint-plugin-babel#rules) (`babel/no-unused-expressions`) instead of the regular one (`no-unused-expression`).

I just tested this today in my project and it works great (only 3 extra deps) It would be even better though our `eslint-config` supported this out of the box. Care for a PR, @LarsDenBakker ? 😃

**Comment by LarsDenBakker** [comment]
Doesnt eslint do stage 4 by default? But lets use babel eslint then.

**Comment by tmsns** [comment]
Yes, they are working on it: https://github.com/eslint/eslint/issues/12642, but they are blocked for now.

Also, some teams might not be able to upgrade to the latest eslint yet. The bug will probably only be fixed in one of the upcoming 7.x releases.
