### ISSUE TITLE
[demoing-storybook] allow for remark plugins inside mdx transforms.

### ISSUE THREAD

**Issue by tlouisse** [open-wc/open-wc#1269]
It would be nice to be able to allow some AST based transformations of mdx files running through es-dev-server.
It would allow us to tweak documentation/demo contents by writing our own plugins, but also to use existing plugins (for instance to support emojis).

I was thinking about something like below:

In `.storybook/main.js`:
```js
module.exports = {
  esDevServer: {
    ...
    remarkPlugins: [
      images,
      [emoji, { padSpaceAfter: true }],
    ],
   ...
}
```

In `@open-wc/demoing-storybook/src/sharedcreateMdxToJsTransformer.js`, where `mdx` method gets called, we can add the plugins like:
```js
const jsx = mdx.sync(mdxText, {
  remarkPlugins: pluginsProvidedByUser,
})
```
Also see: https://mdxjs.com/advanced/plugins

@LarsDenBakker @daKmoR Would it be ok if I do a merge request for this?

**Comment by LarsDenBakker** [comment]
I think we should only support this if regular storybook supports it too, and with the same API.

**Comment by tlouisse** [comment]
Ok, what would be the reaon for that? Do you see any dangers?
What is the reason to do transpilation inside @open-wc in the first place?

**Comment by LarsDenBakker** [comment]
The goal of `@open-wc/demoing-storybook` is to have less building going on, otherwise you might as well use `@storybook/web-components` directly with webpack.

We want to keep the same, or as similar as possible, API as regular storybook. This way we don't have to do extra documentation, make design decisions etc. It also makes it easier to merge changes back upstream with storybook so we can keep our footprint minimal.

mdx is pretty cool, but has it's quirks too. For web components regular markdown would actually work fine, so we might redirect our efforts for providing a solution with regular markdown instead.

**Comment by tlouisse** [comment]
Ah yes indeed, that was the reason again. Makes sense :) Would be nice if Storybook adopts this. 

So maybe consider it whenever you want to support regular markdown? (since remark is written for regular md asts and this wouldn't align with Storybook anymore).

We kind of need it to be able to extend our @lion documentation, where we partially want to replace  paragraphs or demos. For now we can do a workaround by intercepting dev-server and do `mdx -> ast -> mdx` before `mdxjs` kicks in, but this is not ideal.

Can I keep this issue open as a request for the pure md (without x) version?

**Comment by LarsDenBakker** [comment]
This is now possible with `storybook-addong-markdown-docs`
