### ISSUE TITLE
[scoped-elements] demos/docs code does not support extending elements

### ISSUE THREAD

**Issue by daKmoR** [open-wc/open-wc#1272]
we have the following code in 

`page-a./indexjs`
```js
const html = createScopedHtml({
  'feature-a': FeatureA,
  'feature-b': FeatureB,
});

export class PageA extends HTMLElement {
  // ...
  connectedCallback() {
    render(html`
      <feature-a></feature-a>
      <feature-b></feature-b>
    `, this.shadowRoot);
  }
}
```

this is basically a side effect and registeres `feature-a`...

now it is not possible to extend without registering `feature-a` 🙈 

`ExtendedPage.js`
```js
import { PageA } from 'page-a'; // triggers side effect already
import { FeatureExtended } from '...';

const html = createScopedHtml({
  'feature-extended': FeatureExtended,
  'feature-b': FeatureB, // do I need this?
});

export class ExtendedPage extends PageA {
  // ...
  connectedCallback() {
    render(html`
      <feature-extended></feature-extended>
    `, this.shadowRoot);
  }
}
```

# Strawman proposal Mixin

Ideally, you could use a static get

```js
export class ExtendedPage extends ScopedElementsMixin(PageA) {
  static get scopedElements() {
    const parentEls = super.scopedElements;
    delete parentEls['feature-b'];
    return {
       ...parentEls, 
       'feature-extended': FeatureExtended,
    }
  }
}
```

### Strawman proposal convention

alternatively, you could have a convention for how to get the scoped html

```js
let html;
export class ExtendedPage extends PageA {
  constructor() {
    // ...
    this._registerSubElements();
  }

  _registerSubElements() {
    html = createScopedHtml({
      'feature-a': FeatureA,
      'feature-b': FeatureB,
    });
  }
````

**Comment by LarsDenBakker** [comment]
It's a side effect in the sense that importing a module will add an entry to the module graph, it doesn't interfere with anything. We could defer registration until the first render of a template perhaps.

**Comment by LarsDenBakker** [comment]
A static class field is quite interesting too from build-time optimization perspective, but it can't be used by sub templates.

The ideal would be if we have a way to plug into lit-html, so that all lit templates used by a web component are rewritten and can use the static field. Then it really behaves the way scoped custom element registries also work. lit-html and lit-element do something similar here, where it passes the element's context to the lit templates to use as `this` when calling event listeners.

**Comment by manolakis** [comment]
I like the idea of the static class field. Extending a class should extend also its scope. Also, we could do a lazy registration, doing it at the moment we are processing the Html.

 ```js
export class ExtendedPage extends PageA { // PageA extends the ScopedElementsMixin
  static get scopedElements() {
    return {
       ...super.scopedElements,
       'feature-a': FeatureAExtended, // overrides the previous 'feature-a' tag name
    }
  }

  connectedCallback() {
    render(this.html`
      <style>:host { display: block; padding: 10px; border: 2px solid #ccc; }</style>
      <h3>I am page A</h3>
      <feature-a></feature-a>
    `, this.shadowRoot);
  }
}
```

Although `feature-b` is in the scope it does not become registered because it is not used.

I would like to find a better solution for `this.html`, but we need to pass the scope to the Html processor.

**Comment by tmsns** [comment]
Should `ExtendedPage` actually be able to retrieve the `scopedElements` of its parentElement `PageA`? What if `pageA` is still stuck at the version 1 of `feature-b` and `ExtendedPage` needs to use a new feature of version 2?

```javascript
export class ExtendedPage extends PageA { // PageA extends the ScopedElementsMixin
 static get scopedElements() {
   return {
      ...super.scopedElements, // `feature-b` version 1 gets railed in
      'feature-a': FeatureAExtended,
   }
 }

 connectedCallback() {
   render(this.html`
     <style>:host { display: block; padding: 10px; border: 2px solid #ccc; }</style>
     <h3>I am page A</h3>
     <feature-a></feature-a>
     <feature-b attributeOfVersion2="true"></feature-b> 
   `, this.shadowRoot);
 }
}
```
It could be left over to the developer to know when to use `super.scopedElements`.

If `PageA` and `ExtendedPage` share the same scope, they could actually share the same scope.

`scope.js`
```javascript
export const html = createScopedHtml({
  'feature-a': FeatureA,
  'feature-b': FeatureB,
 'feature-extended': FeatureExtended,
});
```
This could even be done at project level, but it would mean that all dependent modules get loaded all the time, or do some smart sets or dynamic loading even.

**Comment by LarsDenBakker** [comment]
I've put together a demo of using a mixin, and hooking into `lit-html` rendering directly.

https://webcomponents.dev/edit/DQRqzOW9uMj0HUDLXysH

The great thing about this is that we don't need to create our own `html` tag, we can apply the transformation to regular lit-html templates and we can scope templates per `LitElement` shadow root *including* sub templates. We could even apply this on an existing codebase without requiring code changes. Interesting possibilities :)

Some caveats:

- This doesn't work with shady render, we may need to replicate some code from shady render or ask lit-html for extra hooks.
- Sub templates aren't processed, but because we cache on the template level it doesn't scope the elements again when it's used in a different scope. We would need to change our caching strategy.

**Comment by mzeiher** [comment]
@LarsDenBakker your sample seems to be private, I also created a similar solution for my needs (with the same caveats)
https://github.com/mzeiher/lit-html-scoped-registry-helper

I also like the idea that the template factory handles the scoping, so the html tagged template literal can just be used normally and the element scoping happens relative to the render root instead of template result level

shady render could be supported if the lit-html API changes a bit (I have a fork in a private repository which should work)

There could be several helpers/mixins for different scoping approaches and users could just take the approach which will suit the best.

The solution with the template factory could also enable defering rendering until a scoped registry with dynamic imports (which is quite important for us) are completely resolved.

**Comment by LarsDenBakker** [comment]
@mzeiher it works for me, also when I'm logged out, and it works for other people as well. What kind of error are you seeing?

**Comment by manolakis** [comment]
It works for me also

**Comment by mzeiher** [comment]
Now it woks on my private laptop (got a "not allowed view" error box before) really elegant solution, as I already said I like the idea of binding the scope to the render root instead of TemplateResult!

**Comment by manolakis** [comment]
@LarsDenBakker looks very promising!

I have to read about the `eventContext` to know how it works. About the cache, I think that maybe we could bind the template cache to the element class, so we would have multiple smaller caches, one for scope, instead of just only one.

**Comment by daKmoR** [comment]
more food for thought - API wise we could also do

```js
import { html, setHtml } from '@open-wc/scoped-elements';
```
then in the Mixin we could use setHtml in the constructor/connectedCallback which could read the static get ...

that way for users it would still be just a static import for html but we could modify it via the Mixin...

**Comment by manolakis** [comment]
I've been playing a little with @LarsDenBakker demo and I did some updates.

https://webcomponents.dev/edit/yfsOiGuQnCFMdaGs1vGa

Basically:
- I'm decorating the render, so shaddy render should work again.
- I bind the cache to the element class, so sub templates are correctly parsed. Also I had to replace the `TemplateResult` because in shared templates both elements share the same `TemplateResult` instance, so it was not a cache problem only.
- I'm deferring the definition of elements so when you extend the scopedElements those elements not used in your template are not defined.
- I changed the way tags are created, using the user suggested tag with `'owc-'` prefix as the base tag to know in DOM that it's an auto-generated one. The motivation of this change is because I found that using classNames is useless when source code is minified, creating tags like `c-a`, `c-b`, etc.
- `@open-wc/scoped-elements` exports two functions, `html` and `createElement`.

```js
import { hmtl, createElement } from '@open-wc/scoped-elements';
```

I'm not sure how this changes affect in performance yet  :-/

**Comment by LarsDenBakker** [comment]
@manolakis I think we're on to something here :) We can compile away the regexp by turning the template literals into arrays with special markers. 

I threw something together here: https://webcomponents.dev/edit/7gUfBeqB7f2n9vkoGe5H how it would look like... I made changes in `index.js` and `transform.js` and added a `scoped-tag.js` file.

This isn't 100% correct yet, as I think the template should be moved outside the class to be a constant but I need to look into that a bit more.

Very curious to see how these two implementations stack up to the current implementation in terms of performance.

**Comment by manolakis** [comment]
Fixed by https://github.com/open-wc/open-wc/commit/9868bc7a1bc94d4e54651c92d458f3b413a1ebda
