### ISSUE TITLE
webpack-index-html-plugin not processed stylesheet

### ISSUE THREAD

**Issue by devalexqt** [open-wc/open-wc#1294]
webpack-index-html-plugin don't process stylesheet link via any loaders.
```
<html>

<head>
    <link href="../style/index.css" type="text/css" rel="stylesheet"> <!-- not processed??? -->

        <style>
            .test0 {
                display: block;
                background-color: bisque;
            }
        </style>
</head>

<body>
    <h1 class="test0">Hi from HTML bundle!!!</h1>
        <script>
            (function () {
                var message = 'hello inline script';
                console.log(message);
            })();
        </script>

        <script type="module"   src="../js/index.js"></script>

</body>

</html>
```
webpack config:
```
const path = require('path');
const WebpackIndexHTMLPlugin = require('@open-wc/webpack-index-html-plugin');

const devMode = process.env.NODE_ENV !== 'production';


module.exports = {
    mode: devMode ? "development" : "production",
    devServer: {
        contentBase: path.join(__dirname, './dist'),
        compress: true,
        port: 9000
    },
    entry: path.resolve(__dirname, './src/views/index.html'),

    output: {
        filename: '[name].[chunkhash].js',
        chunkFilename: '[name].[chunkhash].js',
        path: path.resolve(__dirname, 'dist'),
    },
    module:{
        rules:[
            {
                test: /\.css$/,
                use: [
                    "css-loader",
                ]
            },
        ]
    },//module

    plugins: [new WebpackIndexHTMLPlugin({
        minify:false,
    })],
};
```

**Comment by LarsDenBakker** [comment]
This isn't a goal for `webpack-index-html-plugin` to support, I recommend using `webpack-html-plugin` for that.

**Comment by devalexqt** [comment]
Wait a minute, html as entry point it's not only js script links, it also, style, image, etc. And without this features loader not usable at all.
Also, `webpack-html-plugin` is not a entry point! 
We need more complex solution from `webpack-index-html-plugin` .

**Comment by LarsDenBakker** [comment]
To elaborate more on this topic, I agree that `webpack-html-plugin` doesn't support using html as entrypoint. That's why we created `webpack-index-html-plugin`. 

The scope of the  `open-wc` project has been growing quite a bit lately, and we need to start choosing what we do and don't want to support. Because we generally recommend using rollup, most of our energy is spent there. We are currently creating a new html plugin for rollup which is more modular.

We will be reducing our support for webpack to a minimum, just what's needed to work with web components. For HTML we will change `webpack-index-html-plugin` to only handle using a HTML file as input. For outputting HTML we will recommend using `webpack-html-plugin`.

For now I'll close this issue, as there is nothing actionable for us right now.
