### ISSUE TITLE
[es-dev-server] recommend tsc over babel

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1361]
The babel typescript plugin seemed like a great idea, but there are quite some areas where it falls short. Most importantly there are issues with file extensions, decorators and class fields. 

For `es-dev-server` we should flip around the recommendation to use `tsc --watch` while developing. Although it scaffolds lots of files, it is a better overall dev experience. Separately we could investigate if using https://github.com/rollup/plugins/tree/master/packages/typescript inside es-dev-server (as a plugin) improves the dev experience.

**Comment by vikerman** [comment]
I am trying to recreate the TypeScript setup manually here with `tsc --watch` integrated into different npm scripts - https://github.com/vikerman/open-wc-typescript-starter/blob/master/tsconfig.json. 

It's low tech but it's better than using rollup in es-dev-server because the turn around time I suspect would be much better since rollup is not involved and stays closer to rest of the JS-only tooling and less maintenance that way.
