### ISSUE TITLE
[es-dev-server] check accept header before injecting into HTML

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#1368]
es-dev-server doesn't work for projects using html imports, because html imports request html files with an accept */* header. This causes a false positive in the dev server, which thinks it's serving a regular HTML file.

Instead of only checking the server response content-type header, we should also double check the browser is requesting a text/html file.

**Comment by dancarlocanlas** [comment]
> Instead of only checking the server response content-type header, we should also double check the browser is requesting a text/html file.

Does this refer to the checking being done in `isIndexHTMLResponse` under `utils`?

**Comment by LarsDenBakker** [comment]
Yes indeed

**Comment by LarsDenBakker** [comment]
Closing since this was fixed.

**Comment by davidmaxwaterman** [comment]
I'm just come back to the project that was the reason for this issue to be raised, and I notice the problem is still there. I see that the fix has been merged, so I'm not sure if the fix didn't fix it for me (or the polymer init test case), or if the fix has made it into the most recent release. Any ideas?

Here's my comment on slack:

Hi, I just moved back to this project, and it seems to be having the same problem again...ie requests for message_channel as hanging. I updated the globally installed es-dev-server for my other project (if you recall), and now it doesn't work for this project again. I updated to the very latest, but it still fails. Furthermore, I downgraded to 1.38.2 and it no longer works:
```
  TypeError: (0 , _polyfillsLoader.findJsScripts) is not a function
      at findScripts (/home/davidmaxwaterman/.nvm/versions/node/v12.14.1/lib/node_modules/es-dev-server/dist/utils/inject-polyfills-loader.js:100:58)  TypeError: (0 , _polyfillsLoader.findJsScripts) is not a function
      at findScripts (/home/davidmaxwaterman/.nvm/versions/node/v12.14.1/lib/node_modules/es-dev-server/dist/utils/inject-polyfills-loader.js:100:58)
```
but I think that's a different problem since it fails on the very first request (for index.html).
With the latest es-dev-server:
```
$ npm ls -g es-dev-server
/home/davidmaxwaterman/.nvm/versions/node/v12.14.1/lib
└── es-dev-server@1.54.1 
```
it serves the first 6 requests for message-channel (dev tools says the first is initiated in index.html, and the other 5 from 'other'), but the subsequent (25 - 6) requests remain (all from 'other') as 'pending'.
Es-dev-servers 'debug' output mentions 1 request early on:
```
[es-dev-server]:  "Receiving request: /__es-dev-server__/message-channel"
[es-dev-server]:  "Serving request: /__es-dev-server__/message-channel with status: 200"
```
and 5 more at the end of its output:
```
[es-dev-server]:  "Receiving request: /__es-dev-server__/message-channel"
[es-dev-server]:  "Serving request: /__es-dev-server__/message-channel with status: 200"
[es-dev-server]:  "Receiving request: /__es-dev-server__/message-channel"
[es-dev-server]:  "Serving request: /__es-dev-server__/message-channel with status: 200"
[es-dev-server]:  "Receiving request: /__es-dev-server__/message-channel"
[es-dev-server]:  "Serving request: /__es-dev-server__/message-channel with status: 200"
[es-dev-server]:  "Receiving request: /__es-dev-server__/message-channel"
[es-dev-server]:  "Serving request: /__es-dev-server__/message-channel with status: 200"
[es-dev-server]:  "Receiving request: /__es-dev-server__/message-channel"
[es-dev-server]:  "Serving request: /__es-dev-server__/message-channel with status: 200"
```
