### ISSUE TITLE
[es-dev-server]: node resolution with yarn workspaces goes out of the root directory

### ISSUE THREAD

**Issue by vikerman** [open-wc/open-wc#1408]
I'm trying to create a mono repo using yarn workspaces, with an example directory where I want to run es-dev-server.

<pre>
root
  |
  |__ example
  |          |_ node_modules (empty as everything has been hoisted)
  |          |_ Trying to run es-dev-server here        
  |
  |___ node_modules
             |_ This is the actual place where `import "anything"` resolves to
</pre>

When I try to run es-dev-server it gives the error

Error compiling: Import "tslib" resolved to the file "/home/viks/root/node_modules/tslib/tslib.es6.js" which is outside the web server root, and cannot be served by es-dev-server. Install the module locally in the current project, or expand the root directory. If this is a symlink or if you used npm link, you can run es-dev-server with the --preserve-symlinks option

I'm using yarn and don't want to fallback to using npm with npm link. Changing the rootDir is also cumbersome since too many paths have to be adjusted in a non-trivial manner.

Can we get an option to specify a separate workspaceRoot that default to rootDir but can be above rootDir if needed?

**Comment by LarsDenBakker** [comment]
I've thought about this a lot, but I'm not sure what the correct solution is.

Remember that when serving an unbundled application, all files are requested individually and thus need to be accessible. 

For example if you serve a monorepo, with a root-dir `packages/package-a` and import something from `packages/package-a/node_modules/foo/foo.js` the browser request is `node_modules/foo/foo.js`.

If you import something from `node_modules/tslib/tslib.js` what should the browser request URL be? It can't be `node_modules/tslib/tslib.js` because it would look for `packages/package-a/node_modules/tslib/tslib.js`.

We need some way to let es-dev-server know it's a special type of request, for example:

- `/__es-dev-server-monorepo/root/node_modules/tslib/tslib.js`
- `/node_modules/tslib/tslib.js?es-dev-server-monorepo=root`
- `/node_modules/tslib/tslib.js?es-dev-server-root-dir=/Users/MyUsername/Workspace/my-project/`

But we would need to be careful around handling edge cases, and make it understandable for developers.

My main concern is that none if this would work with a regular web server, and es-dev-server tries to emulate that experience with just some helpers to improve DX. The node resolve logic will eventually be replaced by https://github.com/WICG/import-maps which won't be able to support this either.

**Comment by LarsDenBakker** [comment]
Another possible solution is to allow specifying several directories `es-dev-server` can serve files from. When requesting a file, it will go through the directories in order until it finds a file. Browserify does something similar (https://browsersync.io/docs/options#option-serveStatic) (@ruphin suggested this before)

**Comment by daneah** [comment]
Using `lerna` for monorepo package management also presents this issue.

**Comment by LarsDenBakker** [comment]
@daneah yes and no... if you set the root directory to the root if your repository there is no issue. You need to be able to serve the files you want to use.

**Comment by daneah** [comment]
> @daneah yes and no... if you set the root directory to the root if your repository there is no issue. You need to be able to serve the files you want to use.

Roger that, we were ultimately able to get things working by doing this 👍🏼

**Comment by LarsDenBakker** [comment]
We had some discussions in the team about the multiple directories, but not everyone was quite convinced :)

**Comment by Tansito** [comment]
As reference and continuing with @daneah conversation what we are doing with `lerna` is to link two local packages. In the local package B we install a local package like:

```js
 "dependencies": {
    "my-local-package": "latest"
  },
```

And we try to import that local package:

```js
import 'my-local-package/dist/button/my-button.js';
```

That `my-local-package` is a symlink to the lerna local package and is inside `node_modules`. With that configuration `es-dev-server` can't resolve the path but if we change the symlink copying the entire package it works. I assume that that's because the symlink works but the resolution of that symlink is not accesible.

**Comment by LarsDenBakker** [comment]
es-dev-server has an option to configure how you want symlinks to behave.

It can preserve them so that you can resolve symlinks. This can cause duplicate loading if you symlinks the same file from multiple locations. 

It can also follow symlinks, but then it does need to have access to the files it needs to serve from the symlinks. 

In the end es-dev-server is a static file server, and it has to obey the law of the browser and file system paths. If anyone has an idea of how to improve this developer experience I'm open to hear it.

**Comment by Tansito** [comment]
Well, thanks for the info @LarsDenBakker with the option `--preserve-symlinks` and managing local dependencies with lerna it worked like a charm 😂

**Comment by LarsDenBakker** [comment]
Perhaps we need to make this more explicit in the docs.

**Comment by AliMD** [comment]
same issue
I just run `es-dev-server` from root and address package in browser and its work fine for me
dont need to use lerna at all and I think yarn 1 workspace ir fine, if you need lerna for this case its better to witch to yarn2

**Comment by daKmoR** [comment]
This has been implemented in it's successor `@web/dev-server`
