### ISSUE TITLE
setting the preload option to false still appends preload links to index.html

### ISSUE THREAD

**Issue by veith** [open-wc/open-wc#1418]
With following config 
```
const config = [
  createDefaultConfig({
    input: 'index.html',
    indexHTMLPlugin:{preload: false},
    plugins: {
      workbox: false,
    },
  }),
];
```

the content from `localConfig.entries.files` https://github.com/open-wc/open-wc/blob/277729c0fc158bdd8c1e54d6335b401268090bfb/packages/building-utils/index-html/create-index-html.js#L227-L229 works correct and is not appended. 

The content from `localConfig.entries.preloadedFiles` https://github.com/open-wc/open-wc/blob/277729c0fc158bdd8c1e54d6335b401268090bfb/packages/building-utils/index-html/create-index-html.js#L242-L244  is still appended.

Maybe it should also check for the `localConfig.preload` flag?

```js
if (localConfig.preload && localConfig.entries.preloadedFiles) {
    localConfig.entries.preloadedFiles.forEach(appendPreloadScript);
 }
```

**Comment by LarsDenBakker** [comment]
Indeed it should check for preload. We're releasing a new version of the rollup config pretty soon, which will tackle this. If you really need this now, we could accept a PR to fix this.

**Comment by LarsDenBakker** [comment]
With the new version of the rollup config and HTML plugin preload is no longer configurable. This is because the way rollup works, you need to preload initial imports for performance. 

If you really need some custom behavior you can implement your own inject behavior by setting inject to false. See https://github.com/open-wc/open-wc/tree/master/packages/rollup-plugin-html for more info on that.

Will close this issue, but let me know if you have any questions.
