### ISSUE TITLE
Testing with sinon

### ISSUE THREAD

**Issue by cnagadya** [open-wc/open-wc#1425]
The mock/stub/spies/fakes are not called. [This](https://open-wc.org/testing/testing-sinon.html) example given in the testing docs also fails
```
import { stub } from 'sinon';
import { expect, fixture, html } from '@open-wc/testing';

describe('my component', () => {
  it('calls myFunction when a button is clicked', () => {
    const el = fixture(html`
      <my-component></my-component>
    `);

    // stub a function
    const myFunctionStub = stub(el, 'myFunction');

    // click a button
    el.shadowRoot.getElementById('myButton').click();

    // check if the function was called
    expect(myFunctionStub).to.have.callCount(1);
  });
});
```

`AssertionError: expected myFunction to have been called exactly once, but it was called 0 times`

**Comment by jaredmahan** [comment]
@cnagadya I am experiencing the same issue and this is currently blocking my testing. This example doesn't work in our code base.

**Comment by jaredmahan** [comment]
Can someone help us out and let us know what is going on here?

**Comment by thepassle** [comment]
I can reproduce, I will take a look at this today

**Comment by thepassle** [comment]
We figured out why this is happening:

#1 Assuming your code looks like this, the test will pass:
```js
render() {
  return html`<button @click=${() => this.myFunction()}>click</button>`;
}
```

#2 And this will fail:
```js
render() {
  return html`<button @click=${this.myFunction}>click</button>`;
}
```

The reason is that with #2 the stubbing(/wrapping) of myFunction happens AFTER you give it to lit-html, whereas with #1 you make fixture, stub `el.myFunction`, and _then_ when you click it, it will already be wrapped.

So you can either do: `@click=${() => this.myFunction()}`, and the test as is will pass.

Or go with `@click=${this.myFunction}`, and then in your test:

```js
  it('does the thing', async () => {
    const el = await fixture(html`<my-component></my-component>`);
    const myFunctionStub = sinon.stub(el, 'myFunction');
    el.requestUpdate();
    await el.updateComplete;
    el.shadowRoot.getElementById('myButton').click();
    expect(myFunctionStub).to.have.callCount(1);
  });
```

Alternatively, instead of testing the function has been called, you could test the sideeffects of that function.

We should definitely improve the documentation on this though for sure. I will keep this issue open to track it.

**Comment by jaredmahan** [comment]
Awesome thanks @thepassle for the update that worked for me! If you guys can improve the documentation around this it would help a ton!

**Comment by cnagadya** [comment]
Thank you so much @thepassle :)
