### ISSUE TITLE
[@open-wc/building-rollup] Web Workers showing in bundled index.html

### ISSUE THREAD

**Issue by andyricchuiti** [open-wc/open-wc#1483]
hey team,

thanks for the work in these standards. i'm using web workers and bundling the workers with rollup-plugin-off-main-thread (https://github.com/surma/rollup-plugin-off-main-thread) where it searches for the regex `new Worker` and bundles that file, but the createDefaultConfig is also loading the script into the index.html.

main.js
```
import './app/app.component.js'
const apiWorker = new Worker('./workers/api.worker.js');
const appStateWorker = new Worker('./workers/app-state.worker.js');
```

rollup.config.js
```
import {createDefaultConfig} from '@open-wc/building-rollup';
import OMT from '@surma/rollup-plugin-off-main-thread';

const config = createDefaultConfig({ input: './src/index.html' });

export default {
  ...config,
  plugins: [
    ...config.plugins,
    OMT(),
  ],
};
```

so my dist folder has the right scripts, but the index.html contains
```
function t() {
    ["./main-fffd6547.js", "./api.worker-23ba6621.js", "./app-state.worker-2d8e41a7.js"].forEach((function (e) {
      window.importShim(e)
    }))
  }
```

but i need it to just be
```
function t() {
    window.importShim("./main-fffd6547.js")
  }
```

**Comment by LarsDenBakker** [comment]
Looking at the output, it seems like the OMT plugin injects the worker as entrypoints to rollup which in turn causes them to be loaded in HTML because it picks up all rollup entrypoints automatically.

We have a big update of the rollup config coming up soon which will use our new HTML plugin (https://github.com/open-wc/open-wc/tree/master/packages/rollup-plugin-html). This doesn't suffer from this problem, it will only inject entrypoints that belong to that HTML file. 

If you're patient you could wait a bit, or you could try out https://github.com/open-wc/building-rollup-changes where we've prepared the upcoming changes.

**Comment by andyricchuiti** [comment]
yeah, absolutely! i can wait and do building-rollup-changes in the meantime. thanks so much

**Comment by LarsDenBakker** [comment]
This should work properly now with v1 of building-rollup. See https://github.com/open-wc/open-wc/blob/master/packages/building-rollup/README.md and https://github.com/open-wc/open-wc/blob/master/packages/building-rollup/MIGRATION.md. Could you try it out and let me know?

**Comment by andyricchuiti** [comment]
yep! that worked. thank you so much for getting this out! I really appreciate it.
