### ISSUE TITLE
Extract "rel=stylesheet" data from HTML files

### ISSUE THREAD

**Issue by Westbrook** [open-wc/open-wc#1484]
I'd like for for `rollup-plugin-html` to `extractStylesheets` as well as `extractModules`.

I'm not sure if wanting to put the page CSS in the HTML is a byproduct of my stubbornness to support old practices, the desire to force most (hopefully all) `import styles from './styles.css'` to support LitElement (though `rollup-plugin-postcss` also doesn't seem to support the `include`/`exclude` options common to Rollup that I think I'd want to start with to be able to work out conditional processing there) or something else that I'm missing, but I think I want to put `<link rel="stylesheet">` tags in my HTML and have it extract them both for possible `postCSS` processing and to ensure the build takes any files referenced and puts them into dist automatically.

If this made sense to you too, I'd be happy to start putting together a PR with a little guidance on how you thought that could best be added to the plugin.

**Comment by LarsDenBakker** [comment]
I agree this would be good to add to the HTML plugin. I think it's good to start with some use cases we have in mind here, for example some people may want to concatenate multiple stylesheet links into one file while others may want to just inline the stylesheet into the HTML.

**Comment by Westbrook** [comment]
Good call! Do you keep a map of how we're managing various `<script>` tag realities? I think this would probably line up 1 to 1 with that, but not sure. Some possibilities off the top of my head:

**A single `<link rel="stylesheet">`**
In the context of a "componentized" front-end, this would seem to be the default as an application's individual components would manage their own styles, and the page level styles would be more about load management and static HTML orchestration.
- do nothing beyond ensuring the file is taken along for the ride (would this automatically put it into the rest of the Rollup pipeline?). if so, this might nullify some of the following options, as we could just allow the user to manage a CSS file themselves.
  - probably opt-out
- surface a `transform` relative option so that custom processing can occur
  - does this nullify the `minify` option?
- surface a `minify` relative option
- surface an `inline` option to inject the CSS into a `<style>` tag

**Multiple `<link rel="stylesheet">` tags**
What are the goals of a user that does this? Even a user that doesn't rely on SASS could leverage `@import` in raw CSS to get this same functionality, right?
- options like the above
- surface a `bundle` option to merge these files
  - nullified by the `inline` option?

Other concepts that might deserve a little thought:
- Above the fold CSS injection
  - I've never used tools for this, and am unsure what sort of guardrails would be needed for a tool like ours to support aligning with a tool like that
- Unused CSS clean up
  - Also a tool I've not used, theoretically, it reads the HTML for selectors and cross-references it to a CSS file, which would seem to occur right at the time that this plugin is doing its work. Could actually be pretty powerful in a Shadow DOM + MPA world in that you could rely on only the initial DOM needing to be styled 🤔
- Interesting option as constructible style sheets get further along to add options to process specifically tagged `<link>` elements into constructible styles, but very future, IMO. 
- I'm sure there's a lot that I've missed.

A lot of things get _simpler_ after the CSS files themselves are "in the Rollup build" as we have more opportunity to say "the power is yours", so we might be able to get away with an early version that ONLY supports doing that and use early adopters to help structure broader support delivery.

**Comment by LarsDenBakker** [comment]
We can emit the CSS files as assets, other plugins can then act on this.

**Comment by LarsDenBakker** [comment]
We only handle module script currently, they are extracted and passed through rollup. Multiple module scripts means multiple rollup entrypoints and multiple files loaded from the final HTML, we don't concatenate them. I think we can follow the same logic, and emit them as assets so that they're available for other plugins as well. 

For inline content there will probably be a difference, inline JS is passed through rollup and not added back as an inline module but loaded externally. For CSS we probably don't want to do this, and the current HTML minifier already minifies inline CSS. But I'm not sure how it handles `@import` statements, are these even allowed in `style` elements? That's something we need to think about.

You're definitely right there are some really interesting use cases here for MPAs, that will take some more time to iron out so let's try and create something we could scale up later on.

By adding files to rollup as assets, other plugins can access them so like you said the power is available for others to extend the behavior. 

Just like HTML we should have an option for transforming the CSS. `transformCss`? Should we rename `transform` to `transformHtml`? Thinking towards the future a bit, we may have different types of assets in the future such as JSON or import maps. Also there might be new ways to load assets like CSS, so the way the resource is included might make a difference. Perhaps we should have a `transformAsset` hook that receives the asset node type and attributes. Something to think about...

We should have some solid defaults, such as concatenating `@import` statements and minifying CSS. [html-minifier](https://github.com/kangax/html-minifier) uses [clean-css](https://github.com/jakubpawlowicz/clean-css) for minifying inline CSS. It has an option for following `@import` statement: https://github.com/jakubpawlowicz/clean-css#how-to-process-remote-imports-correctly. That might be interesting, we could align the behavior for inline and external stylesheets. Do you have any experience with other tools?

**Comment by Westbrook** [comment]
> But I'm not sure how it handles @import statements, are these even allowed in style elements?

This is a good point, I've never even thought to do that!

> Perhaps we should have a transformAsset hook that receives the asset node type and attributes. Something to think about...

I like where you are going with that. I had a short moment where I was thinking: `transform: { html, css, json, etc}` but I think the more general approach is nicer to extend from a user standpoint.

> html-minifier uses clean-css for minifying inline CSS.

I've been working a lot with postCSS lately, which is nice, but if we do get the CSS into the asset pipeline, something a little simpler is probably the right way to go there as a default. Also, the less we do, the more others can do with our output.

So cool, where do we start? 😉

**Comment by LarsDenBakker** [comment]
Let's break it down into some steps (which we can probably merge separately):

1. Extract non-js resources, emit them as rollup assets and inject rollup asset name back into the HTML
- which resources to extract? link rel stylesheet, img src, what else? probably we want to make this configurable somehow... 
- should this be enabled or disabled by default? smart defaults?

2. Add a hook for transforming the asset
- A breaking change would be unfortunate, so let's create a `transformAsset` function:

Strawman:

```js
export default {
  plugins: [
    html({
      transformAsset({ tagName, attributes, assetPath }) {
        console.log(tagName); // 'link'
        console.log(attributes); // { rel: 'stylesheet', href: 'theme.css' }
        console.log(assetPath); // 'theme.css'
      }
    })
  ]
}
```

Names are not set in stone of course. I'm not sure we need assetPath since we already have attributes, but it might be nice to know what the plugin is going to use for processing.

3. Create a way to inline critical CSS
I'm not sure if this should be in the HTML plugin, or if this should be in a separate plugin. We can spend some time thinking about this.

4. Figure out how to handle inline resources
We already minify inline CSS, and customizing it can be done by modifying the HTML minifier. I think that's ok to start, we can spend some time thinking how/if we want to improve on this. Especially to support `@import` in inline styles, if it works at all.

**Comment by LarsDenBakker** [comment]
I've implemented this in the new HTML plugin here: https://github.com/modernweb-dev/web/pull/774
