### ISSUE TITLE
[@open-wc/testing-karma] how to test image import?

### ISSUE THREAD

**Issue by Taewa** [open-wc/open-wc#1707]
Hi all,

I'd like to know what's the best practice of testing js module while the module imports image file.

```javascript
// my-module.js
import { LitElement, html } from 'lit-element';
import * as abc from '.abc.gif';

render() {
  return html`
    <img src="${abc}" />
  `
}

```

This works fine during the development and able to see the `abc.gif` image properly on Chrome browser.

Now, I'd like to run a unit test by using `@open-wc/testing-karma@3.0.0`.

When I run `karma start karma.conf.js` and check the Chrome browser's console, I see the following error message.

`Failed to load module script: The server responded with a non-JavaScript MIME type of "image/gif". Strict MIME type checking is enforced for module scripts per HTML spec.`

Ok, normally I am not supposed to import non-js file. But Webpack might help me.

Then I tried to use `karma-webpack`.
I got the following error message.

`Refused to execute script from 'http://localhost:9876/base/packages/PATH/abc.gif?transform-systemjs' because its MIME type ('image/gif') is not executable.`

How other people test their js module that import image files?

I have seen some code like `import './some-icon.js';` which export svg file.
Is this only way to go? or is there any other workaround?
Any comment would be helpful.

I use nvm.
I tried with `v12.2.0` and `v8.16.0` just in case :)

Thanks.

**Comment by LarsDenBakker** [comment]
As you found out, the browser doesn't know what importing an image means. What are you importing? The path to the file? The image as a js object? A text representation of the image? The image as base 64?

If you're using webpack during development there are probably some loaders which handle this for you. In that case, we recommend using karma-webpack so that development and testing are in line. You shouldn't use `@open-wc/testing-karma` in that case, as it's intended for use without webpack. You could check the karma-webpack docs to see how to set it up.

For a buildles approach with images, we recommend embedding them in JS if they're SVG or using `import.meta.url` to get the image URL relative to your module:

```js
// my-module.js
import { LitElement, html } from 'lit-element';

const abc = new URL('.abc.gif', import.meta.url).pathname;

render() {
  return html`
    <img src="${abc}" />
  `
}
```

**Comment by Taewa** [comment]
Thanks for the response @LarsDenBakker !

I did a couple of tries by your comment.
Indeed, `new URL('abc.gif', import.meta.url).pathname;` works with unit test!
That's good but Stroybook is broken.

So I added `@babel/plugin-syntax-import-meta` in `.storybook/.babelrc` (of course after install that dependency)

```javascript
 "plugins": [
    "@babel/plugin-syntax-import-meta",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-object-rest-spread"
  ],
```
it didn't work.

Next try!
I added `@babel/plugin-syntax-import-meta` in `.storybook/webpack.config.js`

```javascript
const defaultConfig = require('@open-wc/demoing-storybook/default-storybook-webpack-config.js');

module.exports = ({ config }) => {
  return defaultConfig({
    config,
    transpilePackages: ['lit-html', 'lit-element', ...],
    options: {
      plugins: [
        "@babel/plugin-syntax-import-meta"
      ]
    }
  });
};
```
Also no luck.

I found that I can actually use as static image instead of use `import`.
( https://storybook.js.org/docs/configurations/serving-static-files/#2-via-a-directory )
That work in Storybook but it sort of violating our file structure. (but it solve Storybook issue AND karma unit test both!)

That makes me think why it's so hard to put a simple `gif` file in html?

**Comment by LarsDenBakker** [comment]
Storybook uses webpack, which doesn't support import.meta unfortunately even though it's implemented in all major browsers...

You could use https://github.com/open-wc/open-wc/tree/master/packages/webpack-import-meta-loader

I think it's useful to use one distribution system throughout your stack so that you don't have to keep fixing problems.

Webpack style:
- webpack-dev-server
- storybook
- karma-webpack

open-wc "buildless" style:
- es-dev-server
- @open-wc/demoing-storybook (uses storybook without webpack)
- @open-wc/testing-karma
