### ISSUE TITLE
[E2E Testing] Scoped elements selectors

### ISSUE THREAD

**Issue by MateWW** [open-wc/open-wc#1751]
Hello,
We are looking for some good way to select scoped element inside e2e test.
Currently we are trying to use some attributes to mark elements but it is ugly workaround which forces us to pass mostly unused attribute because of tests.

**Comment by Westbrook** [comment]
Have you ever looked into https://testing-library.com/docs/dom-testing-library/intro and the way it focuses on binding your E2E tests on the accessible structure of your DOM rather than on "test markers"? Regardless of how scoping the selector changes the naming of elements in the DOM tree, they should, in theory, and possibly in test, maintain the same "accessibility tree", which could make their approach highly productive here.

Out of the box, Testing Library isn't very targeted to shadow DOM, but I've been playing with vending a version with support for piercing for the sake of testing. Not to say it's 100% the best answer here, but if it were one that you were interested in, I've been looking for the right excuse to get an initial release of the Shadow Dom Testing Library onto NPM.

**Comment by MateWW** [comment]
@Westbrook I'm not sure but testing library also recomend to add specific attribute `data-testid` to elements? I guess it's not worst idea but we are looking for some solution which will allow us to avoid that.
