### ISSUE TITLE
[CLI] Upgrade doesn't yield expected results

### ISSUE THREAD

**Issue by ARuzek** [open-wc/open-wc#1772]
When using the "Upgrade an existing project" on the CLI, the only package updated was to `"lint-staged" : "^10.0.0"` even though I have other other packages such as the following that I would assume have updates available based on change log and version numbers on the npm library listings. For example:

```
    "@open-wc/building-rollup": "^1.0.0",
    "@open-wc/demoing-storybook": "^2.0.0",
    "@open-wc/eslint-config": "^2.0.0",
    "@open-wc/prettier-config": "^0.1.14",
    "@open-wc/semantic-dom-diff": "^0.15.6",
    "@open-wc/testing": "^2.0.0",
    "@open-wc/testing-karma": "^3.0.0",
    "@open-wc/testing-karma-bs": "^1.3.62",
```
On further inspection, I see that scaffolding a new project also uses these package versions above. Is this to be expected? 

Nothing is wrong with my repo, I'm just curious.

**Comment by Westbrook** [comment]
"Upgrade an existing project" is meant for adding tooling to a project that doesn't currently have it. So if you have a component repo that doesn't have Storybook, use "Upgrade an existing project" and you can add Storybook to that repo, etc. If you are looking to upgrade the actual package versions in your project, please rely on `yarn upgrade` or `npm update` to manage your lock files, or manually point specific dependencies in your `package.json` to newer/different version numbers before running `yarn install` or `npm install`. 

The generators work with the oldest equivalent package version and up `"@open-wc/building-rollup": "^1.0.0",` in order to allow your package manager of choice to make the best decision about the version to add to your project while still supporting the functionality expected by the generator. Generally, when breaking changes are required is the only time we make a concerted effort to alter those base version levels.

If you have any other questions, feel free to reach out, but as you've mentioned that you don't have any issues in your project, I'm going to close this for now. Thanks for reaching ou!
