### ISSUE TITLE
Update the project generator to web test runner

### ISSUE THREAD

**Issue by thepassle** [open-wc/open-wc#1842]
We should start using `@web/test-runner` for the [project generator](https://github.com/open-wc/open-wc/tree/master/packages/create)

More info on @web/test-runner here: https://modern-web.dev/docs/test-runner/overview/

Need more guidance, help, or instructions to get you started? Reach out to us on the Polymer slack 🙂

**Comment by trystan2k** [comment]
Hi,

I am looking into this and have a question: The idea is to remove Karma and replace it with WTR or have both options and the developer can select one or the other ?

If we want to have both, I think it would be better to split the `What would you like to add` in 2 (one for Linting and Demoing and the other for Test where only one - Karma or WTR can be selected) otherwise it would be possible to select both Testing options. What do you guys think ?

**Comment by LarsDenBakker** [comment]
The goal is to have just WTR in there. We won't recommend karma for new projects, but we will keep supporting it for existing projects.
