### ISSUE TITLE
Update the project generator to web dev server

### ISSUE THREAD

**Issue by thepassle** [open-wc/open-wc#1843]
We should start using `@web/dev-server` for the [project generator](https://github.com/open-wc/open-wc/tree/master/packages/create)

https://modern-web.dev/docs/dev-server/overview/

Need more guidance, help, or instructions to get you started? Reach out to us on the Polymer slack 🙂

**Comment by trystan2k** [comment]
Hi @thepassle,

I can work on this, if it is ok for you

**Comment by thepassle** [comment]
Absolutely 🙂

**Comment by trystan2k** [comment]
Hi,

I have started to work on this and have some doubts. I have created a [Draft PR](https://github.com/open-wc/open-wc/pull/1858) with the changes I have so far

I have updated all entries for `es-dev-server` for `@web/dev-server` for the generators but in the main.js for the storybook (for example [here](https://github.com/open-wc/open-wc/blob/master/packages/create/src/generators/app-lit-element/templates/static-demoing/.storybook/main.js#L8)) it has some setup for `esDevServer` when running storybook. 
Looking into `demoing-storybook` it uses the `es-dev-server` node API to configure and execute es-dev-server (for example [here](https://github.com/open-wc/open-wc/blob/master/packages/demoing-storybook/src/start/cli.js#L7)).

My question is, should I also updated `demoing-storybook` to use @web/dev-server ? If the answer is yes, should I do in another PR or in the same one ?

Also, if it needs to done, I am not sure how to handle the `esDevServerCliOptions` [here](https://github.com/open-wc/open-wc/blob/master/packages/demoing-storybook/src/start/readCommandLineArgs.js#L75-L84) since `es-dev-server` export its cli options but `web-dev-server` [does not](https://github.com/modernweb-dev/web/blob/2b3b242871f3447dbd6d00ba238f7db11a756be3/packages/dev-server/src/config/readCliArgs.ts#L22).  Should `web-dev-server` be changed to export it or there is an alternative ?

And also [readCommandLineArgs](https://github.com/open-wc/open-wc/blob/master/packages/demoing-storybook/src/start/readCommandLineArgs.js#L82) from `es-dev-server` receives 2 params (argv and config) while web-dev-server [readCliArgs](https://github.com/modernweb-dev/web/blob/2b3b242871f3447dbd6d00ba238f7db11a756be3/packages/dev-server/src/config/readCliArgs.ts#L94) which I suppose do the same thing, just receive 1. When migrating to `web-dev-server` should it just pass the first argument ?

Besides the `demoing-storybook` and the generators, is there any other place where it is needed to update `es-dev-server` ?

Please let me know if you have any questions or if anything is not clear and how to proceed.

Thank you !

**Comment by LarsDenBakker** [comment]
@trystan2k thanks for looking into this. For now, we can skip the changes to demoing-storybook. There are some other pending breaking changes there, we can do it all in one go.
