### ISSUE TITLE
[testing-karma] Update karma-mocha

### ISSUE THREAD

**Issue by keillaf** [open-wc/open-wc#1844]
### Description

I found a low vulnerability because of the dependency [karma-mocha](https://www.npmjs.com/package/karma-mocha). Is it possible to upgrade the version for one without  this vulnerability?

https://www.npmjs.com/advisories/1179

![Screen Shot 2020-09-14 at 14 48 48](https://user-images.githubusercontent.com/67276156/93120332-9648bd00-f699-11ea-9c6a-a68918f3582e.png)

**Comment by ARuzek** [comment]
I did some investigation. `karma-mocha` major update to version **2.x.x** does update the minimist dependency to  `"minimist": "^1.2.3"` but the `@open-wc/testing-karma` and  `@open-wc/testing-karma-bs` dependency for `karma-mocha` is still at `"karma-mocha": "^1.0.0",` so it's not going to auto-update to version 2 because major updates could be breaking. 

I would ask that a more experienced contributor check in on this update to `"karma-mocha": "^2.0.0",` to make sure it doesn't break anything, please.
