### ISSUE TITLE
[polyfills-loader] Polyfills for common DOM methods

### ISSUE THREAD

**Issue by ianldgs** [open-wc/open-wc#1849]
Currently, there's no polyfill solution out there for the following methods:

- Node.prototype.addEventListener | 1321
- Node.prototype.append | 433
- Node.prototype.prepend | 452
- Node.prototype.before | 440
- Node.prototype.after | 461
- Node.prototype.remove | 290
- Node.prototype.replaceWith | 731
- Node.prototype.children | 245
- Node.prototype.firstElementChild | 262
- NodeList.prototype.forEach | 158
- Element.prototype.closest | 333
- Element.prototype.toggleAttribute | 243
- Element.prototype.matches | 133
- Element.prototype.classList | 4450
- Element.prototype.getAttributeNames | 182
- MouseEvent | 405
- CustomEvent | 279

It's probably possible to add them to the loader from here: https://github.com/msn0/mdn-polyfills.
IMO it would be great to get it out-of-the-box, even if as a single file included on all browsers that do not implement at least one of those.

**Comment by justinfagnani** [comment]
FYI, lit-html and LitElement are going to start using `Node#append`, `Node#remove`, `Element.classList`, `Array#flat` and others.

**Comment by LarsDenBakker** [comment]
This is definitely something we should look into. The complicated part we need to figure out how to group polyfills together, and to decide when to load them. 

Loading many small individual polyfills is slow, but so is loading many unused polyfills. We need to find some middle ground. One policy we've been maintaining is to not load any polyfills for the latest few of modern browsers. This way we have some more budget for users who are on older browsers.

**Comment by justinfagnani** [comment]
On our end, we are indeed not using APIs that aren't available on current browsers, so we'll pretty much only need these polyfills on IE11. We're moving towards a compatibility stance where it's acceptable to require larger polyfills on IE11 in order to increase perf or reduce file size on modern browsers, as we move IE to legacy support and prepare to drop it when feasible. So far most of the DOM polyfills we need aren't really that big, so a bundle of them should be fine - IE's only used on desktop too.

btw, I might add `getAttributeNames` to the mix :)

**Comment by LarsDenBakker** [comment]
I think that's doable, but what about browsers that support modules but not something like array flat?

**Comment by justinfagnani** [comment]
Array#flat would be part of JS polyfills. I presume there's a number of ways for apps to load that, including core-js.

**Comment by LarsDenBakker** [comment]
Yes but we still need a strategy for deciding when to load what. For things like `fetch` it's simple because you can check a single API. But DOM APIs and JS polyfills are lots of different APIs, we probably need to make some groupings and decide on watermarks. 

For example right now we make a high level split between browser that support modules (module script, import.meta and dynamic import) and those that don't. We serve es modules to the former and systemjs, core-js etc. to the latter.

**Comment by LarsDenBakker** [comment]
Not stale

**Comment by ianldgs** [comment]
@LarsDenBakker here is a proposal, for 2 bundles and their watermarks:

```
!toggleAttribute: (Edge 18)
    include toggleAttribute (Edge 18)
    include getAttributeNames (Edge 18)
    include classList (Edge 17 - full)
    include replaceWith (Edge 17)
    include after (Edge 17)
    include before (Edge 17)
    include prepend (Edge 17)
    include append (Edge 17)
```

```
!matches:
    include matches (edge 15)
    include closest (edge 15)
    include firstElementChild (edge 12)
    include children (edge 12)
    include remove (edge 13)
```

`addEventListener (ie 9, not needed)`

**Comment by ianldgs** [comment]
@LarsDenBakker would you give a green light on this based on my previous comment?
My company might allow one of us to work on this at some point.
If someone from `open-wc` starts working on this, please let me know.

**Comment by LarsDenBakker** [comment]
I noticed that many of these are being added to the webcomponents polyfills as well, so we need to see what they cover. So we will get to this at least when the new version of lit-html/lit-element comes out. In the meantime you can configure custom polyfills in the polyfills loader, so that should work as well.

**Comment by LarsDenBakker** [comment]
This issue has been sitting here for a while. We discussed it in the team as well a while ago, and right now we don't want to take on the maintenance of a polyfills bundle/package. The loader is pluggable, so users can plug in their own sets of polyfills. We will continue to support a default configuration that works for popular libraries like lit-html/lit-element, so when the new version comes out we will make sure we load the correct polyfills there.

**Comment by justinfagnani** [comment]
Note that we've added a number of DOM methods needed by the next version of lit-html and LitElement to the web components polyfill loader.
