### ISSUE TITLE
Scaffold files for demo and testing are not generate when running in non interactive mode

### ISSUE THREAD

**Issue by dmondev** [open-wc/open-wc#1864]
**Steps to reproduce**

Run npm init with the following params

`npm init @open-wc --type scaffold --scaffoldType wc --features linting testing demoing --typescript true --scaffoldFilesFor testing demoing --tagName ui-elements --writeToDisk true --installDependencies npm `

Verify that test and story files are not created in the generated project.

**Comment by trystan2k** [comment]
Hi,

This seems to be because of how `prompts` handle the overrides of the answers. In this case, it does not execute the `onState` method and because of that `scaffoldOptions` is empty https://github.com/open-wc/open-wc/blob/master/packages/create/src/generators/app/index.js#L81-L88 (so there is no matching options with `scaffoldFilesFor `)

One possible solution would that in the `execute` method of `AppMixin` we add a pre-process that checks if `overrides` is provided and add `features` options to `scaffoldOptions`, that way we let prompts do its work later.

Something like this:

```
      let scaffoldOptions = [];

      if (overrides && overrides.features) {
        scaffoldOptions = overrides.features.filter(feature => feature !== 'linting')
      }
```

If this is an acceptable solution, please let me now and I do the PR. 

Thanks !

**Comment by trystan2k** [comment]
Since the create project was moved to a separated repo, I did the PR there: https://github.com/open-wc/create/pull/5

Let me know if you have any comments/suggestions/questions !

**Comment by LarsDenBakker** [comment]
Not stale... @trystan2k still interested in picking this up?

**Comment by trystan2k** [comment]
> Not stale... @trystan2k still interested in picking this up?

Hi,

Yes. 

If you are ok with the solution I propose, I can do the PR !

**Comment by LarsDenBakker** [comment]
Yep sounds good to me
