### ISSUE TITLE
Build <script src=...> content into index.html

### ISSUE THREAD

**Issue by mercmobily** [open-wc/open-wc#1885]
I have a SPA which uses external libraries such as EJS, Moment, web-animations-js and Codemirror.
I have this in my `rollup-config.js`:

````
const copyConfig = {
  targets: [
    { src: 'node_modules/moment/min/moment-with-locales.min.js', dest: 'dist/node_modules/moment/min/' },
    { src: 'node_modules/moment-timezone/builds/moment-timezone-with-data.js', dest: 'dist/node_modules/moment-timezone/builds/' },
    { src: 'node_modules/moment-precise-range-plugin/moment-precise-range.js', dest: 'dist/node_modules/moment-precise-range-plugin/' },
    { src: 'node_modules/ejs/ejs.min.js', dest: 'dist/node_modules/ejs/' },
    { src: 'node_modules/datalist-polyfill/datalist-polyfill.min.js', dest: 'dist/node_modules/datalist-polyfill/' },
    { src: 'node_modules/web-animations-js/web-animations-next.min.js', dest: 'dist/node_modules/web-animations-js/' },
    { src: 'node_modules/jshint/dist/jshint.js', dest: 'dist/node_modules/jshint/dist/' },
    { src: 'src/v2/lib/sharedCodeFile.js', dest: 'dist/src/v2/lib/' },
    { src: 'node_modules/jshint/dist/jshint.js', dest: 'dist/node_modules/jshint/dist/' },
    { src: 'node_modules/codemirror/lib/codemirror.js', dest: 'dist/node_modules/codemirror/lib/' },
    { src: 'node_modules/codemirror/lib/codemirror.css', dest: 'dist/node_modules/codemirror/lib/' },
    ...more CodeMirror lines...
````
Then in my index.html I have:

````
    <script src="node_modules/moment/min/moment-with-locales.min.js"></script>
    <script src="node_modules/moment-timezone/builds/moment-timezone-with-data.js"></script>
    <script src="node_modules/moment-precise-range-plugin/moment-precise-range.js"></script>
    <script src="node_modules/ejs/ejs.min.js"></script>
````

I need to copy those resources over so that they actually work. 
Some of them (like moment) are actually available as ES6. But things like codemirror or web-animations-js aren't.

Is there an easy, neat way to replace those `<script src="...">` statements into inline contents in the index.html file?

The SPA I am running has a very flaky internet connection, and I need to minimise the number of hits on the server on load.

**Comment by daKmoR** [comment]
I don't think there is an automated way for that right now 🙈
e.g. right now only `type="module"` packages are considered for the js module graph.

all other types of resources like `<script src="...">` or `<img src="...">` or css, picture source, ... are currently not (yet) detected or processed.

For a long time we wanted to implement this but no one found the time yet to actually do it 😅
it will probably "hook" into a similar system like
https://modern-web.dev/docs/building/rollup-plugin-import-meta-assets/

in order to then also be able to hash and rename those files (which would allow for long/infinite caching times)

### What can you do now?

"Manually" merge all these files into one and import this one file. Could be a separate rollup, node, gulp or whatever task that does it only on demand e.g. only if you add a new dependency. And then add only this one file into your html `<script src="my-merged-file.js">` 

If you are curious about implementing this detection and processing for `@open-wc/rollup-plugin-html` we can offer more guidance and help 🤗

**Comment by mercmobily** [comment]
Gosh, given that this is basically for legacy libraries (hopefully, soon enough everything will come as an ES module!) and given that there is an _easy_ workaround... I am not sure it makes sense to spend time on this!
