### ISSUE TITLE
[testing] Conflicts and code/package duplication when following testing guide

### ISSUE THREAD

**Issue by blikblum** [open-wc/open-wc#1905]
I'm configuring tests for a  new project and found some inconsistencies in the guide:

- In https://open-wc.org/testing/, it recommends the dev.to step by step guide article that uses karma and a few lines below recommends web-test-runner step by step guide.
- In https://open-wc.org/testing/testing.html, expect is imported from @open-wc/testing and in web-test-runner guide from @esm-bundle/chai
- @open-wc/testing depends on mocha v6 and web-test-runner uses mocha v8 (seems its bundled instead of a dependency)
- @open-wc/testing depends on chai and web-test-runner guide suggests @esm-bundle/chai

**Comment by LarsDenBakker** [comment]
I understand the confusion, we're working on some updates to the website where we should clarify this better.

For clarification, we recommend using web-test-runner. 

`@open-wc/testing` is a superset of chai, registering default plugins and exporting some helpers for test fixtures and other things. Right now it uses `window.chai`, but we will update it to use `@esm-bundle/chai` later as well.

We recommend using `@esm-bundle/chai` if you're just looking to use chai. That's why we use it in the examples at modern-web since it's not directly web component based.
