### ISSUE TITLE
How to deploy/publish a modern and legacy javascript file for a web component ?

### ISSUE THREAD

**Issue by BnitoBzh** [open-wc/open-wc#1920]
I have create a new project with the `npm init @open-wc` command.
All options activated (a web component project, with typescript, and demoing, etc ...)
Now i want to build/publish my project, not a HTML file ... But simply a module and legacy version of my web component that can be deployed on s3 to allow my customers to use this webcomponent on their websites.

Is there someone have a the perfect config file to do this ?

**Comment by LarsDenBakker** [comment]
Currently we recommend doing building only at the final distribution level. This is because there are quite a lot of things to keep in mind when bundling, such as browser target, polyfills and shared dependencies, which are hard to decide from a component point of view.

That being said, you could use the `createBasicConfig` option from our rollup package: https://github.com/open-wc/open-wc/tree/master/packages/building-rollup#non-spa-projects

**Comment by BnitoBzh** [comment]
Ok i understand but the `createBasicConfig` only speaks about multiple html file generation. I do not need HTML file, only JS files with a modern and legacy build. The legacy build must be IE11 compatible with the fetch polyfill.
The default behavior of @open-wc is to build SPA app or reusable web component for app development. 
I want to distribute a web component, that can be directly integrated in a basic HTML page (for example a wordpress integration). And the user choose itself if he want to integrate the modern or legacy build.

**Comment by LarsDenBakker** [comment]
The basic config does JS bundling. It gives an example of using the HTML plugin if you need it, but it's not required. You could also set up your own rollup config, it's not a very complicated tool.

Our configs don't bundle any polyfills because this can be problematic when multiple scripts on the page include conflicting polyfills.
