### ISSUE TITLE
JSDoc Recommendations for properties, attributes, and events, etc.

### ISSUE THREAD

**Issue by goatandsheep** [open-wc/open-wc#198]
Should there be standards for documenting properties, probably using jsdoc / typedoc? If so it could describe:

* properties, attributes
* events fired

**Comment by daKmoR** [comment]
yeah for that we don't have a clear recommendation yet 🙈 
typedoc seems good for all the js for sure; for attributes it will probably be something in line of https://github.com/w3c/webcomponents/issues/776
for properties, events there is nothing really out there right now... maybe someone can join the discussion and/or implement something so we can piggyback on the attributes solution?

**Comment by goatandsheep** [comment]
Jsdoc actually has [@fires](http://usejsdoc.org/tags-fires.html) for events. I really like what the vscode team has done!

**Comment by goatandsheep** [comment]
[There's also JSON Schema](https://react-jsonschema-form.readthedocs.io/en/latest/) which has Mozilla support

**Comment by Georgegriff** [comment]
On this, something i really liked about polymer based components was the documentation, you have all of your events/properties documented along side the demos. 
Is there any way with story book to inject your jsdoc comments to some form of api docs page? (i've never used storybook so might be a dumb question)

**Comment by Georgegriff** [comment]
For someone who had never used storybook i found it all very daunting in terms of demoing. One of things I loved about Polymer was how simple it was to document and demo your element. It would just parse your jsdoc comments and you provide some basic demos in a demo folder. I generated a component using the vanilla yeoman template on your site and I was a little overwhelmed and didn't know where to start. Just some feedback for someone familar with web component, and really wants a nice documentation/demo experience.

**Comment by daKmoR** [comment]
yes that is currently "lacking" we are moving to `npm init open-wc` so the generators are getting a little out of sync (we have a PR open to fix that... still needs some finishing touches)

with storybook 5 we should be able to show documentation and even provide a nice playground with your full properties API... I think that can be a nice place to bring all the info together next to the live demos :)

as this is pretty new we don't yet have a separate demo up and running somewhere but you can look at https://open-wc.org/demoing/ where you will see a gif showing it 👍  let us know what you think 🤗

**Comment by goatandsheep** [comment]
@georgegriff I second on the idea to follow Polymer's method of documenting. I liked that a lot

**Comment by thepassle** [comment]
So I think really two things are being discussed here:
- Demoing(/docs) with storybook
- A jsdoc kind of documentation

I think, like george said, not everyone will want to set up a storybook for their project, so should we have recommendations for that?

**Comment by daKmoR** [comment]
There is a new analyzer on the block 🤗 

looks really promising 💪 
https://github.com/runem/web-component-analyzer

**Comment by Georgegriff** [comment]
This looks great!

**Comment by goatandsheep** [comment]
@thepassle would it be a lot to make the web-component analyzer tool above part of the standard?

**Comment by thepassle** [comment]
Iirc this is from the same author as the vscode lit-plugin, which personally im a big fan of. 

I think we could look into this, and I'd have to try it out more, but im also wondering where we should put this. We do have a Storybook section and a Types section.

Also curious to hear what the other guys think about this.

**Comment by runem** [comment]
I think it would benefit the entire ecosystem if we could agree on, and recommend, a common way of documenting web components. This will enable much better IDE-support, linting and docgen. I think a really good start would be to agree on some common jsdoc tags :-)

I like the comment by Justin [here](https://github.com/w3c/webcomponents/issues/776#issuecomment-443018559) because I think it sums up the situation very well. In my comment I will specifically be focusing on jsdoc tags.

I proposed some jsdoc tags in [web-component-analyzer](https://github.com/runem/web-component-analyzer#-how-to-document-your-components-using-jsdoc). I took the freedom to choose some myself, but I'm very open for changing them if you have any concerns/requests. Below I will describe each of these jsdoc tags in details and why I chose them.

Compared to [Justins comment](https://github.com/w3c/webcomponents/issues/776#issuecomment-443018559) my proposal covers:

- Tag name: [@element](#🏷-Tag-name)
- Slots/Permitted content: [@slot](#📬-Slots)
- Events fired: [@fires](#⚡️-Events)
- Properties: [@property](#👪-Properties)
- Attributes: [@attribute](#👪-Properties)
- CSS variables: [@cssprop](#💅-CSS-Custom-Properties)

It doesn't cover the following, but I think we can always add more later on.

- DOM interface: methods, superclass, implemented interfaces
- [CSS Shadow Parts/Themes exposed](https://github.com/fergald/docs/blob/master/explainers/css-shadow-parts-1.md)
- Permitted parents
- Default / Permitted ARIA roles

# Proposed jsdoc tags

## 🏷 Tag name

This jsdoc tag documents that the declaration is tied to a custom element with a certain tag name. This jsdoc tag is especially useful if your `customElements.define` is called dynamically eg. using a custom function.

### Syntax

```
@element [<tagName>]

Synonym: @customelement
```

**Note**: I can't find any standard camel cased jsdoc tags. Therefore I suggest that `@element` would be the recommended jsdoc tag because I think it's easier to read than `@customelement`.

### Example

```js
/**
 * @element my-element
 */
class MyElement extends HTMLElement { ... }
```

### Thoughts

Polymer recommends adding `@customElement` to custom elements in their [section about documenting custom elements](https://polymer-library.polymer-project.org/3.0/docs/tools/documentation). I couldn't find documentation about specifying a tag name alongside the jsdoc tag (maybe I'm not looking the right place?), but I found the approach in [this](https://github.com/Polymer/tools/blob/dc391830fec747bb6164109157cd3a24302e346a/packages/analyzer/src/test/static/polymer2/test-element-19.js) file in a test for the polymer analyzer.

In addition it seems like [sometimes Polymer uses `@element`](https://github.com/PolymerElements/app-layout/blob/master/app-drawer/app-drawer.js) instead, but I couldn't find any documentation for this jsdoc tag.

## 📬 Slots

This jsdoc tag documents which slots names are available within your custom element.

### Syntax

```
@slot [{<permittedTagNames>}] [<slotName>]
```

### Example

```js
/**
 * @slot - This is a comment. Using the "slot" jsdoc without a name indicates an unnamed slot.
 * @slot left - Content placed to the left
 * @slot right
 */
class MyElement extends HTMLElement { ... }
```

I suggest it should be possible to further indicate which tag names are permitted inside a slot by specifying string literals in the jsdoc type like this:

```js
/**
 * @slot {"my-item"} - You must only use "my-item" tag names for unnamed slots.
 * @slot {"div"|"span"} footer - You must only use "div" and "span" for slots named "footer".
 */
class MyList extends HTMLElement { ... }
```

### Thoughts

This jsdoc tag seems to be [used by the Ionic team](https://github.com/ionic-team/ionic/blob/master/core/src/components/button/button.tsx).

## ⚡️ Events

This jsdoc tag documents which custom events your custom element dispatches.

### Syntax

Jsdoc already has a tag for specifying which events a can be fired: [@fires](https://jsdoc.app/tags-fires.html). I think this can be used for documenting events.

```
@fires [{<detailType>}] <eventName>

Synonym: @emits
```

**Note** I actually suggested using `@event` instead of `@fires` in `web-component-analyzer`, but I actually think `@fires` would be the best approach because it's standard jsdoc (see my thoughts below).

### Example

```js
/**
 * @fires change - Dispatched when the content of this element changes.
 * @fires my-event
 */
class MyElement extends HTMLElement { ... }
```

I suggest it should be possible to further indicate the type of the `detail` property on the CustomEvent like this:

```js
/**
 * @fires {string} change - A change event where detail is the new text of this element.
 */
class MyElement extends HTMLElement { ... }
```

### Thoughts

I'm in doubt if/how it should be possible to also document that an event `bubbles`, is `cancelable` or is `composed`, but I think it's out of scope for now.

Polymer suggest using the standard jsdoc tag [@event](https://jsdoc.app/tags-event.html) like [this](https://polymer-library.polymer-project.org/3.0/docs/tools/documentation#events):

```js
/**
 * Fired when `element` changes its awesomeness level.
 *
 * @event awesome-change
 * @param {number} newAwesome New level of awesomeness.
 */
```

It's not documented anywhere but I assume that this jsdoc block must be somewhere within the class declaration. [Here's an example with 'iron-input'](https://github.com/PolymerElements/iron-input/blob/master/iron-input.js#L114).

The challenge I've had with this approach is, that if compiling with Typescript this entire jsdoc block with `@event` disappears from the declaration file because it's not attached to any emitted declaration. I like using the standard [@fires](https://jsdoc.app/tags-fires.html) better because I think it's lightweight and more in line with the other jsdoc tags proposed.

In addition `@fires` documents that the class fires a certain event and `@event` can be used to document an event itself. Therefore I think `@fires` better communicates the purpose which is to tell that a particular custom element can dispatch a certain event.

It's also important to note that these two tags do not exclude each other. In fact I still think it should be allowed to use them together (like the following example) because it's part of standard jsdoc:

```js
/**
 * @fires awesome-change
 */
class MyElement extends HTMLElement { ... }

/**
 * Fired when `element` changes its awesomeness level.
 *
 * @event awesome-change
 * @param {number} newAwesome New level of awesomeness.
 */
```

Therefore I would suggest using `@fires` only with an `@event` declaration if you want to document more complex event types. And I wouldn't suggest using an `@event` jsdoc block without a corresponding `@fires`.

## 👪 Properties

This jsdoc tag documents which properties are available on your custom element.

### Syntax

Jsdoc already has a tag for specifying properties: [@property](https://jsdoc.app/tags-property.html). I think this can be used for documenting properties on custom elements.

```
@property [{<jsdocType>}] <propertyName>

Synonym: @prop
```

### Example

```js
/**
 * @property {"red"|"green"} color - The color of this element
 * @property person - A person object that this element must show
 */
class MyElement extends HTMLElement { ... }
```

It also has syntax for [optional and default values](https://jsdoc.app/tags-type.html).

```js
/**
 * @property [person] - Optional property
 * @property {"red"|"green"} [color="red"] - Optional property with default value
 */
class MyElement extends HTMLElement { ... }
```

## 👪 Attributes

This jsdoc tag documents which attributes are available on your custom element.

### Syntax

I think we can have exactly the same syntax/rules as the standard `@property` jsdoc tag, but with the name `@attribute` instead.

```
@attribute [{<jsdocType>}] <attributeName>

Synonym: @attr
```

Regarding `<jsdocType>`: It's worth noting that an attribute in reality of course is always a string type. However I think it's important to be able to indicate if the attribute expects a string, string-union, number or if it's a boolean attribute. Therefore `<jsdocType>` would be the type that this attribute coerce to.

I also think it should be possible to use this tag in jsdoc on properties in order to indicate that the attribute has a relationship to the property (see example below). I think this is important because often properties and attributes are in sync with each other.

### Example

```js
/**
 * @attribute name
 * @attribute {"red"|"green"} color - The color of this element
 * @attribute {"small"|"large"} [size="large"]
 */
class MyElement extends HTMLElement {
  /**
   * This property can be set using either an attribute or the property itself.
   * @attr my-attribute
   */
  myProperty = "hello";

  /**
   * When omitting <attributeName> on the @attr jsdoc tag we document that there exists a corresponding attribute with the same name as the property.
   * @attr
   */
  text = "hello";
}
```

## 💅 CSS Custom Properties

This jsdoc tag documents which CSS custom properties are available on your custom element.

### Syntax

```
@cssproperty <cssPropertyName>

Synonyms: @cssprop, @cssvariable, @cssvar
```

Writing `<cssPropertyName>` with or without the `--` prefix is optional.

### Example

```js
/**
 * @cssprop --element-font-size - A CSS custom property that sets the font size.
 * @cssprop --element-border-radius
 * @cssprop [--element-color="red"]
 */
class MyElement extends HTMLElement { ... }
```

### Thoughts

Maybe it would be relevant to also document the type of the custom property like `@cssprop {number} --font-size`, but here I'm in doubt how to indicate types like "color" or "px". Therefore I think it's out of scope for now.

# Conclusion

Here I proposed some jsdoc tags that could be recommended for documenting web components. I'm very open for suggestions and concerns.

If we agree on some jsdoc tags, I would gladly write a more official guide/recommendation :-)

**Comment by LarsDenBakker** [comment]
@runem I really like this! I'd say let's all go for `web-component-analyzer` and we can always iterate and improve where needed. But by far the most important thing of all is the fact that everyone follows the same standards.

How well does this interop with typescript?

**Comment by thepassle** [comment]
Im a big pro for this. We could have a new page under `Developing -> Documentation`(/documenting) maybe? And maybe refer to it from the `types` page

**Comment by bennypowers** [comment]
What can we do to document class mixin functions a la polymer cli's `@appliesMixin`?

**Comment by goatandsheep** [comment]
@bennypowers my understanding is that much of the mixin capacity of polymer [will be deprecated in polymer 4](https://github.com/Polymer/polymer/issues/5240) and they were previously deprecated in react. I'm not sure if we should recommend people even use mixins.

**Comment by bennypowers** [comment]
@goatandsheep thanks for the notes. Let's take this opportunity to dispel a misconception. The React mixins which were considered "harmful" aren't the same thing as [js class mixins](http://justinfagnani.com/2015/12/21/real-mixins-with-javascript-classes/), which are the only way to share code or implement "multiple inheritance", unless you use a library like [hybrids](https://hybrids.js.org) which abstracts over element classes and `cusyomElements.define`. Class mixins are still very much the recommended way to do that for vanilla and vanilla-like libs.

Side note, there will be no Polymer 4 library. The polymer team [now recommends LitElement](https://www.polymer-project.org/blog/2018-05-02-roadmap-faq) for new projects.

Please forgive typos - on Mobile

**Comment by daKmoR** [comment]
## Properties & Attributes

imho we should stay as barebone as possible

therefore for attributes and properties, I would say stick to what works by default and that would be "auto" definitions in the constructor?

e.g. we should make it a simple as possible to get fully documented elements without needing to add arbitrarily double information. (e.g. if you write good custom elements in most cases you only document additional information not declare types/properties that are already clear)

```js
class Foo extends LitElement {
  // these types are just a hint for the updatingElement
  static get properties() {
    return { color: { type: String } };
  }

  constructor() {
    super();
    // this is the "real" type automatically determined (by typescript and js) by setting it to a string
    this.color= ''; 

    // if you want additional information like that it is an attribute we could just add it there?
    /**
     * @attribute {"red"|"green"} color - The color of this element
     */
    this.color = '';

    // only if the default value needs to be undefined/null you are forced to set a specific type yourself
    /**
     * @type {Function}
     */
    this.formatter = null;
  }
}
```
so every property that does not start with an `_` (for until will have protected properties) should be considered a public property. So usually there is no need to annotate it extra with a `@property`. Only if there is no default type.

another thought - jsDoc should be used to enhance the documentation by writing valuable information besides types - an example (Note: there is no @property as the type can be auto determined - the text written is purely to provide better documentation and intellisense)
```js
/**
 * The title to display inside the title bar
 * - should be less then 100 characters
 * - should not contain HTML
 * - should be between 2-5 words
 *
 * @example
 * // DO:
 * el.title = 'Welcome to the jungle';
 *
 * // DON'T:
 * el.title = 'Info';
 * el.title = 'Welcome to <strong>the</strong> jungle';
 * el.title = 'We like to talk about more then just what sees the eye';
 */
this.title = 'You are awesome';
```

I did some exploration in this direction already https://dev.to/dakmor/type-safe-web-components-with-jsdoc-4icf#how-does-it-work

## element
The class usually does NOT dictate the custom element name.
So it's probably better to define it where it actually happens.

```js
/**
 * @element 
 */
customElements.define('foo-bar', SomeThing);
```
can the tag name `foo-bar` and the Class `SomeThing` be auto read in this case or do we need to provide it in the jsDoc?

## Slot & CSS Custom Properties
using `@slot` && `@cssproperty` on the class level looks good to me 🤗 

## Events

I am not sure why would you need to declare them separately on the class "again"?

if I have this code
```js
someFuntion() {
  this.dispatchEvent(new CustomEvent('foo', { ... }));
}
```
it should be good enough to know that there is an event fired right?
e.g. rule could be to add
- every `this.dispatchEvent`
- every `new CustomEvent('foo', { compose: true })` as it will go outside as well

If I want additional documentation something like this should be good enough?
```js
someFuntion() {
  /**
   * This is my awesome event will allow you to do...
   */
  this.dispatchEvent(new CustomEvent('foo', { ... }));
}
```

what do you think?

**Comment by runem** [comment]
I agree that we should stay as barebone as possible, and that as many features as possible, like properties and events, should be analyzed when possible, to prevent adding double information to our components 😊

I actually support it with [web-component-analyzer](https://github.com/runem/web-component-analyzer). Here I analyze features like `class fields`, `new CustomEvent("foo")` and `static get observedAttributes() { return ["my-attr"]; }`, so it's unnecessary to specify them in JSDoc (I also work on analyzing [property assignments in the constructor](https://github.com/runem/web-component-analyzer/issues/22) at the moment). 

Web components come in many flavors (eg. LitElement and Stencil), so I built WCA with an architecture that makes it easy to add support for library specific syntax like LitElements `static get properties() { return { color: { type: String } }; }`. In WCA `"Vanilla custom elements"`, `JSDoc` and `LitElement` are just flavors, and different flavours can co-existing in the same web component. For example I could choose to make a `LitElement`, implement `static get observedAttributes` and add a `@slot` JSDoc tag. 

While I agree with you, I still think it's relevant that it's possible to specify all information using JSDoc, because it's needed under some circumstances. In the rest of my comment I will try to outline why/when I would recommend using JSDoc tags sometimes :-) 

## Custom helper functions
Where I think JSDoc really shines is when it's not possible to statically analyze the code. Sometimes we need to analyze a Web Component built with custom helper functions.

For example, I could have built my own function that generates a tag name and defines the element:
```javascript
class MyElement extends HTMLElement { ... }
defineElement(MyElement);
```

Now it would make sense to use the `@element` JSDoc because `customElements.define` is not present in the code:
```javascript
/*
 * @element my-element
 **/
class MyElement extends HTMLElement { ... }
defineElement(MyElement);
```

## Properties & Attributes

I like your example, and I would also recommend doing it that way (and that's a very interesting [blog post](https://dev.to/dakmor/type-safe-web-components-with-jsdoc-4icf#how-does-it-work)!). To add to your example, the only situation where I would use the `@attribute` JSDoc tag on the class declaration is if I'm going to use the attribute ONLY from CSS (so it's not present in the Javascript at all):

```javascript
/**
 * @attribute {boolean} disabled - Disables this element
 */
class Foo extends LitElement { ... }
```

The same principle applies to the `@property` JSDoc, or if a custom helper function is used to setup the component. 

## Element

In your example the `@element` is actually not needed, because an analyzer would simply analyze the `customElement.define` function call. However as mentioned before I would use `@element` if it's not statically analyzable like this: 

```javascript
customElement.define(generateTagName(), MyElement);
```

I would like `@element` to be used on the class declaration because the aim of this JSDoc tag is to **tie together a tagName and a declaration** (just like a `customElements.define` statement would do). Maybe the `<tagName>` should be required and not optional alongside this JSDoc (so it's not possible to just use `@element` alone):
```javascript
/*
 * @element my-element
 **/
class MyElement extends HTMLElement {
}

customElement.define(generateTagName(), MyElement);
```

## Events

Again, I agree, and I think the `@fires` JSDoc tag should only be needed when the event dispatching is not statically analyzable (if you use a custom helper function to dispatch your events). In fact, right now WCA is be able to properly analyze your example :-)

## Consuming Web Component Libraries
Here's a point to make about Web Components and editor support.

I built [vscode-lit-plugin](https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin) as a Typescript language service. Now I will give you an overview of what challenge I encountered when consuming web components from a library.  

In a TS language service you can analyze all project-specific code (so everything is good here), but you only can only analyze declaration files (d.ts) from library code. Therefore an element (where it's easy to analyze the corresponding javascript), would just look like this to me:
```typescript
export class MyElement extends HTMLElement {
  myProp: string;
  static readonly observedAttributes: string[];
  value: string;
}
```

The analyzer wouldn't be able to tell anything about this custom element other than its properties. I see different solutions to this challenge: 
  1. Find, parse and analyze the corresponding js-file (it would require a lot of extra work for the machine, so I don't like this approach)
  2. Ship JSDoc with the custom element like `@attribute my-attr` and `@element my-element` (this would be supported out of the box if we agree on a JSDoc format).
  3. Extend the global TS interface `HTMLElementTagNameMap` with the element (This would only partially help, because now we only know `tag-name` + `properties`).
  4. Ship JSON metadata alongside the Web Component.
 
While I think both 2, 3 & 4 should be possible (2 & 3 is already possible with `vscode-lit-plugin`), I think the best solution in this case is to define a common JSON format for Web Components that can be shipped with the library. It would be really interesting to also look into recommending a standard JSON format (after agreeing on JSDoc tags). These JSON files can be built by analyzing the code and JSDoc. This discussion has already started in [this issue](https://github.com/w3c/webcomponents/issues/776). Right now WCA can output `markdown` and [vscode custom html data](https://github.com/Microsoft/vscode-html-languageservice/blob/master/docs/customData.md) (this format only specifies tags and attributes), but I would really like to implement a more general Web Component JSON output format in the future.

## Conclusion
Sorry, now I wrote a wall of text again 🙈

So to conclude, I think your points are great and I agree with you: **it should be as simply as possible to get fully documented elements without needing to add the information twice**. It should be possible (not required) to specify all the same information using JSDoc because it's needed sometimes (see my examples), but the code itself should be analyzed when possible. So we should recommend only reaching out for JSDoc tags when it's not possible to statically analyze the code you write. 

In addition I think next step after discussing a JSDoc format would be to discuss a JSON format that can be shipped with a Web Component library in order to consume web components. I think JSDoc is great when needing to analyze your own code, but I think a metadata JSON file would be more suitable when shipping a library :blush:

**Comment by daKmoR** [comment]
@runem so basically it comes down to this: `JSDoc is in most cases option but can be used to enhance or provide otherwise missing information` - sounds good to me 🤗 

### Consuming Web Component Libraries
I am wondering how heavy 1 would be e.g. if you provide types via jsDoc and "include" the code to your type checking like we do for open-wc - https://open-wc.org/developing/types.html#setup-for-javascript

We do it like that as to the best of my knowledge there is no nice and simple JSDoc to type definitions generator available (although webpack has their own custom solution... )

what ultimately would be nice is to be able to write "just" js with JSDoc and automatically generate typescript definition files (*.d.ts) and web component definition files (how about `my-tag.d.json` ?).

### Side note

as I was just watching https://youtu.be/ViyTYEv9dM8?t=741 ... apparently, Custom Events are sort of discouraged...

**Comment by bennypowers** [comment]
## Update Regarding Class Mixins

I've had some success with the following JSDoc tags:

The Mixin Function:

```js
/**
 * Provides `isSlotted` method to check if a slot has content.
 *
 * @param {*} superclass the class to mix in to
 * @return The mixed class
 * @mixin IsSlottedMixin
 */
export const IsSlottedMixin = superclass =>
  /** @extends { HTMLElement } */
  class extends superclass {
    /**
     * Checks whether a slot has assigned nodes.
     * @param {String=} slotName Slot name to check.
     * @return {Boolean}
     * @memberof IsSlottedMixin#
     */
    isSlotted(slotName) { /* ... */ }
  };
```
The mixing class:
```js
/**
 * <can-has-slot>
 * @customElement
 * @mixes IsSlottedMixin
 */
class CanHasSlots extends IsSlottedMixin(HTMLElement) { /* ... */ }
```

This is working well in simple cases, I have autocomplete and tooltips in Atom (typescript lang server) but is failing if I also apply `@extends LitElement` to the mixing class.
- Without `@extends`, I don't have tooltips for LitElement methods like `requestUpdate`, but I do have them for `isSlotted`,
- but with `@extends` I have tooltips for `requestUpdate` but not `isSlotted`

**Comment by bennypowers** [comment]
stale has no chill

**Comment by hsablonniere** [comment]
Hey Stale, we all want stuffs that's in this thread :p

**Comment by LarsDenBakker** [comment]
We are discussing this with different people within the web component community, we will standardize on a common format.

**Comment by hsablonniere** [comment]
@LarsDenBakker What are the latest news on this?

**Comment by bennypowers** [comment]
Would like to get @runem 's opinion on this, specifically, how would you see static analysis tools that generate custom-elements.json consuming jsdoc for properties ,attributes, methods , etc.

**Comment by bennypowers** [comment]
heel, Stale! Down, boy!

**Comment by bennypowers** [comment]
Should we break this up into smaller issues, maybe?

**Comment by LarsDenBakker** [comment]
I'm going to close this issue, we are still pushing hard for standardizing `custom-elements.json` and discussing with different parties. https://github.com/webcomponents/custom-elements-json is likely where most of the documentation will go, watch that repository for updates!

In the meantime, https://www.npmjs.com/package/web-component-analyzer is your best bet and an excellent choice along with https://github.com/web-padawan/api-viewer-element for generating API docs.

**Comment by goatandsheep** [comment]
I don't understand. How would the web component analyzer create a standard way of documenting components using jsdoc?

**Comment by thepassle** [comment]
We've been pushing to standardize a `custom-elements.json` format, which you can find at the link that Lars mentioned. We think the `custom-elements.json` will open a lot of useful usecases.

Getting that format standardized is the first priority, and it has proven to be a fairly time consuming process so far. Once thats formalized, we can use tools like `web-component-analyzer` to automatically scan our code, based on jsdoc, and generate a `custom-elements.json`. Its important that we can get all of the web component community behind the format as well.

**Comment by goatandsheep** [comment]
Awesome! I must have missed that update previously. Looking forward to it! ❤️
