### ISSUE TITLE
Unexpected identifier

### ISSUE THREAD

**Issue by Taewa** [open-wc/open-wc#2118]
## Expected behavior

Hi,
First of all, it's not 100% @open-wc issue but it's mixed and the error is happening from `@open-wc/testing/index.js`.
Also I'd like to know your opinion.

I am trying to run the cucumber testing with LitElement, Typescript, CucumberJs (+ Cucmber-js-tsflow) and @open-wc/testing.

POC repo is here: https://github.com/Taewa/cucumber-ts-lit-element

When I run the test npm run test, I get a following error.

```
/PATH/cucumber-lit-element/node_modules/@open-wc/testing/index.js:1
(function (exports, require, module, __filename, __dirname) { import chai from './import-wrappers/chai.js';
                                                                                                                   ^^^^
SyntaxError: Unexpected identifier
```

If I understand correctly, it's the node that doesn't understand import and probably Babel can help me.
But what I am not sure is that should I use Webpack (+ Babel ) to bundle `@open-wc/testing` ?
If I do it, should I change the import path from `simple-greeting.step.ts` ?

## Actual Behavior
`SyntaxError: Unexpected identifier`

Describe what happens instead.

Which packages and versions are you using.
`@open-wc/testing": "^2.5.32`

**Comment by LarsDenBakker** [comment]
Something in your build pipeline is messing with the code and changing that file into some other module format. Those files have a special detection to support to support different module formats as well, but in this case it's having an adverse effect.

This will be fixed with https://github.com/open-wc/open-wc/pull/2130 will probably solve this for you... but you can also check if you can drop the build during testing.
