### ISSUE TITLE
Feature request: Add a basic scaffold

### ISSUE THREAD

**Issue by GHNewbiee** [open-wc/open-wc#244]
Hi!

The `Generators` chapter is good enough. I believe that a basic but fully operational and reliable scaffold (`scaffold-basic`) should be added;

**NO!**
- polyfills
- webpack
- building
- linting
- testing
- demoing
- automating

**ONLY**
- frontend setup (100% reliable!!! **install-and-display**!) (just add a note to the doc which web browsers are supported)

**upgrade generators** and  **sub generators** are very good tools! I think that a `polyfills` generator is also required.

Hence, in a hierarchical point of view, the following `*-generators` exist:
- basic
- polyfills (just add a note to the doc which extra web browsers are supported)
- linting-*
- testing-*
- building-*
- automating-*
etc

Tia

PS: I know that at https://open-wc.org/developing/#lit-html a basic start-up is given but for some reasons no-simple components are not rendered! It is not **install-and-display**.

`Update No.1`: Basic start-up has been clarified at the next post.

**Comment by thepassle** [comment]
The repo for those demo's was initially made to make collaboration on them easier since stackblitz doesn't allow collaboration on demo's yet, and were specifically made for usage on Stackblitz. (eg: the import to index.js in the index.html was missing, because stackblitz doesn't need it).

I do agree however that the demos should be able to run without stackblitz. I do know that Stackblitz is implementing a lit-html setup that doesn't do any webpack magic, so when that time comes I'll refactor things to work like that.

As for a minimal setup, if you want the most basic experience, you can follow these instructions:
```
mkdir my-app
cd my-app
npm init
# click through and enter name etc

npm i -D owc-dev-server
npm i -S lit-html lit-element

touch index.html
touch index.js
```

To your scripts in package.json, add: `"start": "owc-dev-server"`

index.html:
```
<html>
	<head>
		<title>My App</title>
		<script type="module" src="./index.js"></script>
	</head>
<body>
	<my-app></my-app>
</body>
</html>
```

index.js:
```
import { LitElement, html, css } from 'lit-element';

class MyApp extends LitElement {
	render() {
		return html`
			<h1>Hello world!</h1>
		`;
	}
}

customElements.define('my-app', MyApp);
```

**Comment by GHNewbiee** [comment]
@thepassle Great! Now all components work! The difference between your writing and the web site instructions is as follow:

*Your instructions:*
```bash
npm i -D owc-dev-server
npm i -S lit-html lit-element
```

*Web site instructions:*
`npm i -D owc-dev-server lit-element`

Does this difference play any role to render failure?

Thanks a lot!

**Comment by daKmoR** [comment]
There is now a Barebone App in
```
npm init open-wc
```

PS: documentation still needs to be updated 🙈 any volunteers 😬

**Comment by thepassle** [comment]
I'll do some work on the docs this weekend
