### ISSUE TITLE
Rollup/Support TypeScript documentation incomplete sentence

### ISSUE THREAD

**Issue by budajeff** [open-wc/open-wc#278]
"Make sure your set your tsconfig.json to compile to"

There is no period at the end of that sentence and I don't understand what it means which makes me wonder if some of the sentence is missing.

I tried following the Rollup+Typescript documentation but I was not able to get it working. Is there an existing repo somewhere that demonstrates how to use Rollup and Typescript?

Thanks

**Comment by LarsDenBakker** [comment]
Thanks for the notice, it should say: `Make sure you set your tsconfig.json target and module field to exnest. This way typescript doesn't do any compilation so that babel can take care of it`.

There is a working demo here: https://github.com/open-wc/open-wc/tree/master/packages/building-rollup/demo/ts

**Comment by daKmoR** [comment]
@budajeff care to do a MR?

**Comment by budajeff** [comment]
Sure I can do that in a few hours.

**Comment by budajeff** [comment]
#281

**Comment by daKmoR** [comment]
thx for the contribution - closed 💪
