### ISSUE TITLE
`npm init @open-wc` doesn't create all necessary files

### ISSUE THREAD

**Issue by Gudine** [open-wc/open-wc#2799]
## Expected behavior

The initiated project should come with all necessary files

## Actual Behavior

Several of the files needed aren't created.

```
√ What would you like to do today? » Scaffold a new project
√ What would you like to scaffold? » Application
√ What would you like to add? » Linting (eslint & prettier), Testing (web-test-runner), Demoing (storybook), Building (rollup)
√ Would you like to use typescript? » Yes
√ What is the tag name of your app shell element? ... example-app

./
├── example-app\.gitignore
├── example-app\assets\open-wc-logo.svg
├── example-app\custom-elements.json
├── example-app\package.json
├── example-app\src\example-app.ts
├── example-app\stories\example-app.stories.ts
├── example-app\test\example-app.test.ts
└── example-app\tsconfig.json

√ Do you want to write this file structure to disk? » Yes
Writing..... done
√ Do you want to install dependencies? » No
```

## Additional context
Windows 10
Node: v20.14.0
npm: 10.7.0
Also happens with pnpm v8.14.1

I also tried to run it on WSL, and it worked there, so it might be a Windows issue

**Comment by Westbrook** [comment]
I'm also not seeing this in macOS, so it seems you may be right that it is a Windows issue. In that you have a windows environment, we'd love to accept a PR to https://github.com/open-wc/create were you able discover the issue here. Even some background on whether you're seeing this same issue across other combinations of answers could be helpful to hunting something down, were you not able to dive into the code yourself.
