### ISSUE TITLE
[Error while running npm start:prod] Uncaught TypeError: Failed to resolve module specifier "lit-element". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by jantillonc** [open-wc/open-wc#299]
Node: v10.15.0 and npm: 6.4.1

I'm using the starter app generator and it comes with the npm run start:prod option which uses http-server. After installing the http-server via npm and trying to run the app by using: npm run start:prod I keep getting the following error when trying to load the page (modified package.json to remove /dist since I kept getting 404 not found and left only the http-server "start:prod": "http-server" ): Uncaught TypeError: Failed to resolve module specifier "lit-element". Relative references must start with either "/", "./", or "../".

Has anyone faced this issue? Been googling around but i cant seem to find a proper solution.

**Comment by thepassle** [comment]
`npm run start:prod` will run a http server that serves the output of your build, which should be located in the `./dist/` folder. If you didnt run a build yet, you may have to run `npm run build`. 

Whats currently happening is that youre serving the `index.html` in the root of your project, which contains an import of lit-element that it can't resolve, because the http-server doesn't know how to.  

So if you want to see the production build of your project run:
```
npm run build # builds your project
npm run start:prod # runs a http server to serve your build on localhost
```

**Comment by jantillonc** [comment]
Thanks Pascal for the quick response! This resolved my issue, i missed the build part of it.
