### ISSUE TITLE
[semantic-dom-diff] Ignores SVG tags

### ISSUE THREAD

**Issue by manrueda** [open-wc/open-wc#396]
semantic-dom-diff ignores svg tags when doing snapshot testing and there is no way to change that with the options. Is that way for a technical reason?

https://github.com/open-wc/open-wc/blob/master/packages/semantic-dom-diff/get-diffable-html.js#L1

**Comment by LarsDenBakker** [comment]
Yes this is due to technical limitations. HTML and SVG have different rules, the current algorithm only knows how to format HTML.

For example SVG has a lot more void elements, which breaks the way we format the code.

I'm not an expert on SVG, but probably we could expand to add support. Perhaps as a separate module if the size ends up being too large. 

Happy to review a PR if you're interested in adding this.

**Comment by manrueda** [comment]
I will check the HTML one to see what i am facing LOL. I will try...

**Comment by LarsDenBakker** [comment]
I am still interested in supporting this

**Comment by LarsDenBakker** [comment]
I am still interested in supporting this
