### ISSUE TITLE
Minor quirks - can you explain why?

### ISSUE THREAD

**Issue by akc42** [open-wc/open-wc#397]
There are a couple of minor issues in my tests, that I don't understand.

1) My element under test has a `render` function that includes an image tag.
`<img id="logo" src="../images/pas-icon-32.png" alt="PAS Icon">`
the logger from the test gives a 404.
`20 04 2019 12:15:41.236:WARN [web-server]: 404: /images/pas-icon-32.png`

I can see that somehow deep in the depths of things web pack is copying files over into my `/tmp` directory.  Is there a place I can tell it pull this icon over?

2) I am trying to track down why my tests are failing so adding a load of console.log statements.  All of them are duplicated in the log (ie there are two lines for each console.log statement).  I am assuming this is a logging issue rather than the actual code running twice.  But can I prevent that?

**Comment by LarsDenBakker** [comment]
1. Our karma config serves static files, so it should be able to find your image if the path is correct. Without seeing the source code it's hard to say. Probably you are expecting to resolve the image relative to your current module, just like modules. However `src` attributes on img elements are resolved relative to the document, the img element has no reference to the module which rendered it.

You can fix this by using import.meta.urk: `<img src=${new URL('../images/pas-icon-32.png', import.meta.url}>`

2. Karma has a bug where console statements are logged by each reporter, there is no way to work around this :( That's why we only run the test coverage reporter when you use `npm run test`. When you use `npm run test:watch` we don't run the coverage reporter, so logs are logged just once.

For debugging you can also visit http://localhost:9876/debug.html to see the tests run in the browser.

**Comment by akc42** [comment]
Thanks for answer to no 1 - correct, I need to use import.meta.url.  I had not picked up on that as a bug.

I am not that fussed about no2 its just whilst I was trying to figure why something wasn't working - which I have now done (imported module was lazily `fetch`ing something only once, so stub'ing the `fetch` wasn't working - instead I have now learnt how to stub the default function of the imported module by importing it into the test script with a rename ahead of the actual element under test and stub'ing it - seems to work)
