### ISSUE TITLE
CSP compliant polyfills loader

### ISSUE THREAD

**Issue by askbeka** [open-wc/open-wc#404]
currently polyfills loader is being injected as [inline script](https://github.com/open-wc/open-wc/blob/master/packages/building-webpack/modern-web-webpack-plugin.js#L207), which is not CSP compliant.

Possible solution would be to create a chunk and include it `script.src`, but it will mean that it will be an extra round trip, which can be mitigated by preloading

**Comment by LarsDenBakker** [comment]
Good point, this is something we should support.

**Comment by askbeka** [comment]
I can create a PR for this.
If you have any input on preferred implementation, please tell

From API perspective, we can provide an option to enable separate chunk, not to break existing functionality.

From implementaion perspective, I think same plugin can be used to create a chunk and add it htmlplugin chunk list

**Comment by LarsDenBakker** [comment]
I don't have any implementation preferences, if you start a PR we can discuss there

**Comment by jhuesos** [comment]
I am going to pick this task. My plan is to add a new comment explaining how I am planning to approach this task. If anyone has any idea, or preferred approach or is already working on it, please let me know.

This option will be an **opt-in** option, so will not introduce any changes to current consumers.

**Comment by LarsDenBakker** [comment]
Did you start on this yet? Due to some issues I need to refactor the plugin and I want to share more code between the rollup and webpack implementation.

**Comment by jhuesos** [comment]
No, I haven't made any changes yet. I was looking into the code and trying to find how to make the change in the best way. I have never done a Webpack plugin before so some learning is (and still) needed.

For what I saw in the modern-plugin, most of the code could be used for both flows, because the generation of the code and the polyfills part can be used for both. The main difference is that content of the file with polyfills, loading function, etc, it should be added as a webpack plugin so it is also minified and added hash to the name, etc. And then part with the webpack-html plugin would have to be changed to preload that file as well.

Lars, maybe you can answer which I doubt I have:

Why the babel polyfills are added as a separate script tag and it is not added in the same way as the other plugins? The only reason I can think of is to make sure the Promise polyfill is loaded since it is needed for the loadScript function

When are you planning to work on this?

**Comment by LarsDenBakker** [comment]
@jhuesos I'm working on it in this PR: https://github.com/open-wc/open-wc/pull/474

I think we can add a `csp` option and create an external script instead of an inline script here: https://github.com/open-wc/open-wc/blob/f32013cf337ca85bc0a83fcb9877ad0c15366d42/packages/building-utils/index-html/create-index-html.js#L151

Then a plugin (webpack or rollup) needs to make sure it picks up the separate loader script file, and add it to the emitted output. For webpack that's here: https://github.com/open-wc/open-wc/blob/f32013cf337ca85bc0a83fcb9877ad0c15366d42/packages/webpack-index-html-plugin/src/emit-index-html.js#L32

Regarding your question: the babel polyfills are loaded as a script because we use a `nomodule` script which is enough to differentiate the browsers which should and should not load it. Other polyfills, such as webcomponentsjs require a feature detection in javascript. This is what the loader script is for.

I'm not sure how 'unsafe' an inline loader script is, I am curious to see what the performance implications are

**Comment by jhuesos** [comment]
So I was exploring how to change this in the current plugin in the code, and with a pretty small change it was possible (I tried and it works), basically this small changes

```js
function createPolyfillsFile(content, filePath) {
  const hash = crypto.createHash('md4').update(content).digest('hex').substr(0, 20);
  const fileName = `my.${hash}.js`
  fs.writeFileSync(pathJoin(filePath, `./${fileName}`), content);
  return fileName;
}

        let scripts;
        if (this.options.cspFriendly) {
          const polyfillsFileName = createPolyfillsFile(minifiedLoadScriptCode, path.join(compiler.outputPath, polyfillsPublicDir));
          scripts = `${babelPolyfills}<script src="${pathJoin(polyfillsDir, polyfillsFileName)}"></script>`;
        } else {
          scripts = `${babelPolyfills}<script>${minifiedLoadScriptCode}</script>`;
        }

```

Of course, this code did the job but it could have been done better.

Regarding CSP, I have a counter question: why we don't also preload the polyfills file? At least the non-babel ones. For modern browsers would be a waste, but it should speed up page loading.

For CSP, disallowing unsafe-inline and unsafe-eval closes the door to 90%+ of XSS attacks, so IMO, the performance degradation (not much probably) is worth it. Since CSP v2 or v3, there is a new feature to allow inline scripts to be added to the website in a secure way but I am not sure how well is supported by browsers. I would have to do more investigation on that.

**Comment by LarsDenBakker** [comment]
@jhuesos I am finishing up the new plugin this week. I'll make sure CSP ends up in there as well.

We don't need to preload polyfill loader because it will be added as a regular script. The browser already scans and preloads any regular `<script src="..">` it finds. We do need to preload the app code because it's added dynamically, in the polyfill loader.

Thanks for the code snippet, will make use of that.

**Comment by LarsDenBakker** [comment]
This has been implemented
