### ISSUE TITLE
Suggestions to improve linting with prettier

### ISSUE THREAD

**Issue by blikblum** [open-wc/open-wc#406]
While trying to add prettier support to a project i've got a few issues:

Did: `yarn add --dev @open-wc/prettier-config`  and added prettier.config.js and .eslintrc.js as suggested

When i saw @open-wc/eslint-config in .eslintrc.js i assumed this was already in the dependency as well as eslint.

Tried to run eslint but did not find. Added eslint manually and tried again. Got: 
Error: Cannot find module '@open-wc/eslint-config'

So i suggest either:

 - Suppress .eslintrc.js suggestion on prettier page
 - Add a note around .eslintrc.js pointing that is necessary to add manually @open-wc/eslint-config if want to use eslint
 - Add @open-wc/eslint-config as dependency to @open-wc/prettier-config

Another suggestion change Linting Error Examples to Linting Format Examples

**Comment by daKmoR** [comment]
or how about making it a suggestion/note? e.g. something like  
"If you are already using eslint make sure to do ..."

overall the suggestions sound good - if you could create a PR we could talk in more details :hugs:

**Comment by DerkJanSpeelman** [comment]
After setting up a project with `npm init @open-wc`, I see this in the `package.json`:
```
"eslintConfig": {
  "extends": [
    "@open-wc/eslint-config",
    "eslint-config-prettier"
  ]
}
```

There is a `project-name.test.ts` code inside the `test` folder that has this import: `import { html, fixture, expect } from '@open-wc/testing';`.

When using the `@open-wc/eslint-config` configuration, I get this error:

```
module "/Users/derkjan/Projects/solar-system-ts/node_modules/@open-wc/testing/index"
'@open-wc/testing' should be listed in the project's dependencies, not devDependencies.eslint(import/no-extraneous-dependencies)
```

Am I the only one who thinks this is weird? The eslint configuration `@open-wc/eslint-config` gives an error on in an example test file, because it's importing `'@open-wc/testing';`.

**Comment by blikblum** [comment]
I think this is not relevant anymore since deprecation of  @open-wc/prettier-config
