### ISSUE TITLE
[webpack-import-meta-loader] Not all backslashes are transformed on Windows

### ISSUE THREAD

**Issue by tmsns** [open-wc/open-wc#476]
When using the webpack loader to rewrite `import.meta`, not all backslashes are being rewritten. This is aspecially breaking on Windows. The issue seems to be in [webpack-import-meta-loader.js#L23](https://github.com/open-wc/open-wc/blob/master/packages/webpack-import-meta-loader/webpack-import-meta-loader.js#L23): `.replace('\\', '/');` should become: `.replace(/\\/g, '/');`

Didn't have the time yet to setup an environment and create a test though.. :-/ Hope someone can help out here. :-)

**Comment by LarsDenBakker** [comment]
I think rather it should be: `.replace(path.sep, '/');`? Are you able to test this?

**Comment by tmsns** [comment]
We can use `path.sep`, but without the global flag, only the first occurrence of the separator will be replaced.

**Comment by LarsDenBakker** [comment]
`new RegExp(path.sep, 'g')` ? :)

I don't have a windows machine, and we don't run nodejs tests in the CI. So these things are a big blind spot for us, which is definitely a problem we need to find a solution for because this path issue keeps coming up

**Comment by LarsDenBakker** [comment]
Sorry I slightly misunderstood, the original code was already only handling backslashes you just wanted to make it global which is indeed correct!

The original code is actually wrong though because on unix I could have a file or folder with a backslash in it and it would be rewritten to a forward slash. So let's change it to `new RegExp(path.sep, 'g')`
