### ISSUE TITLE
Publishing in nexus

### ISSUE THREAD

**Issue by andjimrio** [open-wc/open-wc#547]
Hi!

I am trying to publish my web components. I added the new of my repository in `package.json` like this:
```json
{
  ...,
  "publishConfig": {
    "registry": "<<nexus_repository>>"
  }
}
```

It was work when I run `npm publish`. The problem is the following. When I import to other repository, I must indicate the path of dist folder like this:

```js
import '@wc/wc-image/dist/wc-image';
import '@wc/wc-social-share/dist/wc-social-share';

...
```

In other words, I want to dist folder stay in root, or something that indicate the build. It will be useful if I will import like this:

```js
import '@wc/wc-image';
import '@wc/wc-social-share';

...
```

Are there a operation behind that solve this problem?

**Comment by LarsDenBakker** [comment]
Hi there! This sounds like a question for npm, I'm not sure what we can do about this from `open-wc`?

**Comment by Westbrook** [comment]
@andjimrio I believe what you're looking to ensure is included here in a [`main`](https://docs.npmjs.com/files/package.json#main) entry point in your `package.json`. This might work in concert with a `module` entry point where you to send compiled code to your NPM registry.

This would _likely_ apply to your project via:
```
"module": "dist/wc-image",
"main": "dist/wc-image",
```
But you'll need to test for yourself to be sure.

We don't currently set values to these fields by default, and because they would very easily fall out of date I'm not sure it's a good idea for us to do so. Because of that, I don't think we will be taking up work here, so I am going to close this issue. Feel free to reopen if you think there is something further we could include in our tools in this area.

Thanks!
