### ISSUE TITLE
[es-dev-server] Move index.html to src dir

### ISSUE THREAD

**Issue by JosefJezek** [open-wc/open-wc#578]
I would like to move `index.html` from root overloaded with config files to `src` dir.

I used option `--root-dir=src`, but I got this error...
`GET https://localhost:8080/node_modules/lit-element/lit-element.js 404`

Do you know any solution?

**Comment by LarsDenBakker** [comment]
The server works like a regular web server. It can't serve files outside your root directory, if you change your root directory to `src` it can no longer access your `node_modules`.

We could perhaps think about adding options to configure the index separately from the root directory.

**Comment by LarsDenBakker** [comment]
Let's keep this issue open to add something which explains this to the docs.

**Comment by JosefJezek** [comment]
I don't know Webpack, but `webpack-dev-server` solves this issue.

Check out the repo https://github.com/web-padawan/polymer3-webpack-starter/tree/master/src

**Comment by libor-m** [comment]
Two approaches come to mind:
- root in `src` and 'mount' `node_modules` separately 
- root in top level and use a rewrite rule to serve `src/index.html` as `/index.html`

Both require a little new functionality in the server.

**Comment by LarsDenBakker** [comment]
`webpack-dev-server` doesn't serve regular files, it just bundles everything and serves one bundle.

`es-dev-server` is intended to serve from source, I don't think creating virtual module folder is going to work well.

I've thought about a couple of solutions and updated the docs with these two sections:

## Folder structure
`es-dev-server` serves static files using the same structure as your file system. It cannot serve any files outside of the root of the web server. You need to make sure any files requested, including node modules, are accessible for the web server.

Click read more to view different strategies for setting up your project's folder structure.

<details>
  <summary>Read more</summary>

  ### index.html in root
  The simplest setup where all files are accessible is to place your index.html at the root of your project:
  ```
  node_modules/...
  src/...
  index.html
  ```

  If you run `es-dev-server` regularly from the root of this project, you can access your app at `/` or `/index.html` in the browser.

  ### index.html in a subfoolder
  If you move your `index.html` in inside a subfolder:
  ```
  node_modules/...
  src/...
  src/index.html
  ```

  You can access your app in the browser at `/src/` or `/src/index.html`. You can tell `es-dev-server` to explicitly open at this path:

  ```bash
  es-dev-server --open src/
  # with an app index the open path is adjusted automatically
  es-dev-server --app-index src/index.html --open
  ```

  You can also change the root directory of the dev server:

  ```bash
  es-dev-server --root-dir src --open
  ```

  Now your `index.html` is accessible at `/` or `/index.html`. However the dev server cannot serve any files outside of the root directory. So if your app uses any node modules, they will no longer because accessible.

  If you want your index in a sub folder without this being visible in the browser url, you can set up a file rewrite rule. [Read more here](#rewriting-file-requests)

  ### Base element
  You can set up a `<base href="">` element to modify how files are resolved relatively to your index.html. You can be very useful when your index.html is not in the root of your project.

  If you use SPA routing, using a base element is highly recommended. [Read more](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base)

</details>

In the advanced section:

### Rewriting file requests

You can rewrite certain file requests using a simple custom middleware. This can be useful for example to serve your `index.html` from a different file location.

<details>
  <summary>Read more</summary>

  Set up a configuration file with a custom middleware:

  ```javascript
  module.exports = {
    customMiddlewares: [
      function rewriteIndex(context, next) {
        if (context.url === '/' || context.url === '/index.html') {
          context.url = '/src/index.html';
        }

        return next();
      }
    ],
  };
  ```

  This way from the browser you can request `/` or `/index.html` and it will serve `/src/index.html`. This middleware is run before the dev server's own file serving logic, which will use the rewritten url.

</details>


Can you see if this works for you?

**Comment by libor-m** [comment]
The custom middleware looks like an ideal solution and the example is very helpful. Thanks!

**Comment by JosefJezek** [comment]
The custom middleware is sufficient solution. Thank you.

**Comment by daKmoR** [comment]
perfect - let us know if you need anything else 🤗
