### ISSUE TITLE
[linting] links broken

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#712]
The links on https://open-wc.org/linting/#setup which reference files to copy paste are broken

**Comment by F9Uf** [comment]
Can i try do that? The files that need to fixed are in docs directory, right?

**Comment by erikkroes** [comment]
I believe the files have actually been deleted: https://github.com/open-wc/open-wc/commit/f6efb7a3289babdd4747a93ab692a8e1199efbc1#diff-82f8c92087ad2a953bcbd30fe0b4cabe
So the page would need to be rewritten

**Comment by FonsecaJoao** [comment]
I can work on this one

**Comment by daKmoR** [comment]
@FonsecaJoao sounds good 🤗 

we move the config into `package.json` so we should explain what they need to add 👍 
you can see what in the generator for example for eslint it's  here
https://github.com/open-wc/open-wc/blob/master/packages/create/src/generators/linting-eslint/templates/_package.json

**Comment by FonsecaJoao** [comment]
A little help, because i think i bit off more than i could chewed... I'm still new to this and i'm feeling a total dumb person.

So in order to install i have to copy what is need from _package.json (taking your file as an eg:.) and paste it in my project package.json

`{
  "name": "",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "mocha",
    "lint:eslint": "eslint --ext .js,.html . --ignore-path .gitignore",
    "format:eslint": "eslint --ext .js,.html . --fix --ignore-path .gitignore"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://"
  },
  "author": "",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "mocha": "^6.2.1"
  },
  "description": "### ",
  "bugs": {
  },
  "homepage": "",
  "directories": {
    "test": "test"
  },
  "devDependencies": {
    "eslint": "^6.1.0",
    "@open-wc/eslint-config": "^1.0.0"
  },
  "eslintConfig": {
    "extends": [
      "@open-wc/eslint-config"
    ]
  }
}`

**Comment by daKmoR** [comment]
yes for full linting you will need to take the content of all the `_package.json` of these generators
- https://github.com/open-wc/open-wc/tree/master/packages/create/src/generators/linting-eslint
- https://github.com/open-wc/open-wc/tree/master/packages/create/src/generators/linting-prettier
- https://github.com/open-wc/open-wc/tree/master/packages/create/src/generators/linting

**Comment by daKmoR** [comment]
linting config no longer depends on individual files but providing its settings in the `package.json`
