### ISSUE TITLE
[es-dev-server] Module resolution flag should be an enum

### ISSUE THREAD

**Issue by justinfagnani** [open-wc/open-wc#738]
There are at least four different module resolution modes in play right now:
1. No resolution - like browsers today
2. Node "require-style" resolution - like Node.js today
3. Import maps - resolved based on explicit configuration
4. Node "module-style" - Node.js native module support resolution

`--node-resolve` only allows for selecting 1 and 2. If it were an enum like: `--module-resolution={none | node-require | import-map | node-module}` then it would admit all the possibilities, and potentially new ones if they ever arise.

**Comment by LarsDenBakker** [comment]
Thats really interesting. What is the difference between node esm and require style? Esm doesnt automatically use index.js?

And what would import map resolution do? Polyfill it server side rather than in the browser?

Right now we use es module shims for that, im interested to learn why that might not work out in some cases and how we could implement this.
