### ISSUE TITLE
[testing] Visual / e2e testing with Puppeteer

### ISSUE THREAD

**Issue by web-padawan** [open-wc/open-wc#74]
The experimental support for Firefox in Puppeteer has been just announced: https://github.com/GoogleChrome/puppeteer/tree/master/experimental/puppeteer-firefox#readme

From now on, it is possible to run visual or e2e tests in 2 browsers, making more sense to use Puppeteer - especially because you can run both Chrome and Firefox locally in Travis or CircleCI, without using cloud automation like SauceLabs which takes much more time.

I'm planning to investigate this and will report my findings here. Feel free to join.

**Comment by daKmoR** [comment]
hey, yes I think for testing we will have probably multiple systems covering different parts of an application/component/microfrontend (uh buzzword :p).

As it's now:
- everything in karma

However that is not going to be be enough for all testing needs.

There are some options:
- pure js tests with karma 
  - Why not: jest? I think jest will sadly not be enough - as we still need to make sure all used javascript functions are available in every supported browser
- "integration" tests with karma (e.g. "small - medium" ui elements and their dom api)
- end 2 end tests with?
  - [cypress](https://www.cypress.io/) seems like a very nicest solution with lot's of features (and they are working on (for quite some time now) supporting multiple browsers) Note: [Discussion](https://github.com/cypress-io/cypress/issues/830) about how to query shadowdom is still ongoing.
  - [webdriverio](http://webdriver.io/) a little more low level but also very promising Note: [Discussion](https://github.com/webdriverio/webdriverio/issues/2858) about how to query shadowdom is still ongoing.

So lets add Puppeteer there as well :) So what would it make it the best out of these options? 

We probaly want to experiment with all and then give a recommedation (or even support multiple).
We should definitely have a pro/cons overview and/or have a "why not" section with very good reasons.

**Comment by LarsDenBakker** [comment]
I've worked a lot of webdriver io and puppeteer. I don't really like selenium, but it's the best cross browser option there is now. I'm a huge fan of puppeteer, it's very very stable for all that it does.

With Edge moving to Chromium and Firefox support coming we're only missing out on Safari for cross browser then, so that's a good sign at least.

**Comment by web-padawan** [comment]
AFAIK current prototype for Firefox is using the special build so it might be a bit early to switch to it at this point. I will keep an eye on the status of that project and see how it evolves.

For the screenshot testing, there are other solutions, too. Some are listed here: argos-ci/argos-cli#11
Note there is a storybook example, in particular.

In the `lit-components` project I'm currently using the `vrtest`, same library as Material UI is using. See config here: https://github.com/web-padawan/lit-components/blob/master/test/vrtest.config.js

**Comment by daKmoR** [comment]
I am not sure how we ended up discussing visual regression tests :see_no_evil: 

anyways I think we should go as much as possible with storyboook as this is what we will actually test right?
So here are their infos: https://storybook.js.org/testing/automated-visual-testing/

So of course [chromatic](https://www.chromaticqa.com/) would be best as it's actually the guys that now are responsible for storybook itself.
However as it's not free (even for open source) I think we need an alternative... I took a quick look at everything I could find and for me, it seems [percy](https://docs.percy.io/docs/storybook-for-react) could looks the nicest.

So I guess this will need multiple POCs first to find what makes the most sense.

**Comment by bennypowers** [comment]
As an alternative, consider Cypress. It can support shadow DOM with some helper functions.

https://github.com/cypress-io/cypress/issues/830#issuecomment-402262740

**Comment by AndreasGalster** [comment]
Would be good to include recommended presets for popular CI providers like CircleCI. Trying to run karma tests right now on CircleCI and running into issues since I guess Chrome isn't installed. 

https://github.com/AndreasGalster/udemy-webcomponents-sample-ci

The YAML file in this repo is working via 

```
      - image: circleci/node:latest-browsers
```

And btw tests also don't pass on CircleCI because of dependency issues described in #175 

Afaik the commands mentioned aren't officially supported so I would consider that also experimental @bennypowers. I eventually decided to not yet teach Cypress testing because of the official support. And imo it looks like shadow DOM support is easily still a year away at the very least, it's not even on their roadmap yet.

I think Puppeteer is a better option short-term for testing shadow DOM for e2e. Cypress is still not offering cross-browser as of writing, so in that sense, Puppeteer wins with official support.

**Comment by AndreasGalster** [comment]
FYI it looks like they are looking into WebKit via Puppeteer!

https://github.com/GoogleChrome/puppeteer/issues/3879#issuecomment-459865627

**Comment by web-padawan** [comment]
Sharing the setup I'm currently using in Aybolit:
https://github.com/web-padawan/aybolit/pull/3

**Comment by web-padawan** [comment]
Regarding the tests, one thing where we could use Puppeteer is performance testing.
Created an example: https://github.com/web-padawan/wc-jest-puppeteer-demo

**Comment by web-padawan** [comment]
Closing as this is not in my current list of priorities.

**Comment by ZempTime** [comment]
As an update, we ended up going with WebDriver, although we have some pain points around shadow dom/setting input fields on Firefox.
