### ISSUE TITLE
[karma-esm] IE11 in .browserslistrc fails karma start

### ISSUE THREAD

**Issue by bashmish** [open-wc/open-wc#767]
When I have `IE 11` query in my `.browserslistrc` and start karma like this:

> ./node_modules/.bin/karma start karma.bs.conf.js --coverage --compatibility all

I get the following error:

```
26 08 2019 09:29:57.058:ERROR [plugin]: Error during loading "/path/to/my/node_modules/@open-wc/karma-esm/karma-esm.js" plugin:
  Your browserslist configuration should not include ie 11.
The browserslists configuration is for the modern build.
Use the --legacy flag for a build for legacy browsers.

26 08 2019 09:29:57.554:ERROR [karma-server]: Server start failed on port 9877: Error: No provider for "framework:esm"! (Resolving: framework:esm)
```

First of all, I don't see why this fails the process and not just logs a warning, and next there is no `--legacy` flag anymore, I'm already using `--compatibility all` (you can see this above in my karma start command) which is the replacement for `--legacy`. Any thoughts?

**Comment by LarsDenBakker** [comment]
The thinking behind this is that for the build tools we use `browserslist` to know what browsers to target for the modern build, and then have an optional legacy build for IE11. That's why people shouldn't put IE11 in there. 

We're reusing this in the dev server and karma, which makes the error message incorrect so we need to do something about that.

I'm open to alternative ideas on how to handle this, having multiple builds is not something that blends well with `browserslist`.
