### ISSUE TITLE
[es-dev-serve] serving the build version doesn't work on IE11 while keeping external dependencies

### ISSUE THREAD

**Issue by jdvivar** [open-wc/open-wc#805]
### Steps to reproduce
1. Scaffold a new `test-wc`
```bash
npm init @open-wc --type scaffold --scaffoldType wc --features  --tagName test-wc --writeToDisk true --installDependencies npm
```
2. Following @open-wc recommendations, add a rollup build process
2.1. Add `rimraf`, `rollup` and `@open-wc/building-rollup`
```bash
npm i -D @open-wc/building-rollup rollup rimraf es-dev-server
```
2.2. Add a trivial `index.html` at the root to satisfy the build process:
```html
<!DOCTYPE html>
<html>
    <head>
        <script type="module" src="test-wc.js"></script>
    </head>
    <body>
        <test-wc></test-wc>
    </body>
</html>
```
2.3. Add a compatibility rollup config file `rollup.config.js` to the root, keeping `lit-html` and `lit-element` as external dependencies:
```js
import { createCompatibilityConfig } from '@open-wc/building-rollup';

const configs = createCompatibilityConfig({ input: './index.html' });

export default configs.map(config => ({
    ...config,
    external: [
        'lit-element',
        'lit-html'
    ]
}));
```
2.4. Add a script to build the wc and another one to serve it, in `package.json`:
```json
"build": "rimraf dist && rollup --config rollup.config.js",
"start:build": "es-dev-server --app-index dist/index.html --compatibility all --node-resolve --open",
```
3. Build and serve the project:
```bash
npm run build && npm run start:build
````
4. Check that everything works fine in Chrome, Safari, Firefox... but not in IE11:
<img width="790" alt="Screenshot 2019-09-17 at 12 28 37" src="https://user-images.githubusercontent.com/690017/65034144-b9397780-d946-11e9-96b0-579eae9c2f21.png">

**Comment by jdvivar** [comment]
Hi Pascal, thank you for looking into it.

In my real world example, some components will be importing others, but they won't all live in the same repository. For the sake of this example, I assumed `lit-element` would be of these other components. If I don't set the module as external, rollup will add it in the bundle (in the same big file), creating huge components that don't share anything one with another. To solve this problem, ideally all components will be available for the rollup build, and I guess rollup (à la webpack) will bundle them separately. But to integrate these components with an old architecture, I specifically do need to build them up individually.

For my example to be complete and more representative, all imported modules have to be compiled to ES5/amd (they're not), but as you said, I have come to the conclusion a front end server with a module resolver would be necessary to achieve what I need. When using  the flag `--node-resolve`, `es-dev-server` do solve bare module imports for Chrome correctly, but not for IE11. In my complete example, even solving them correctly won't work on IE11 because, as said before, no ES5/amd modules have being made available, however that's not the reason why it is not working.

Moving forward, we will focus more on an architecture based on a component catalog instead.

**Comment by LarsDenBakker** [comment]
What you're doing is fine, but you need some way to provide lit-element at runtime. 

Because you have the `--node-resolve` flag turned on, `es-dev-server` will resolve the `lit-element` import to an actual path to the file before serving your application. 

This doesn't work on IE11, because there you're not loading es modules but a systemjs build of your application. es-dev-server is designed to operate only on es modules, for development it will transform modules to a compatible format on the fly for IE11 it not meant to serve a pre-built application like this.

You'd have to think about how you're going to provide lit-element at runtime, and use that to run the build. For example you could use import maps, they're polyfillable using `es-module-shims` or you could consider using `systemjs` on all browsers and use it's import map functionality. I believe rollup also supports providing an external import as a global variable.

**Comment by jdvivar** [comment]
Thanks for the input! I have a much clearer idea now about what's wrong with the code 👍
