### ISSUE TITLE
.babelrc interfering with --compatibility when running es-dev-server

### ISSUE THREAD

**Issue by lakshay35** [open-wc/open-wc#822]
command window after running ```es-dev-server --app-index index-es-dev.html --port 8080 --watch src/ --open --compatibility all --node-resolve```
![image](https://user-images.githubusercontent.com/10873132/65697714-613af900-e049-11e9-91be-566b2fec7a49.png)

.babelrc:
![image](https://user-images.githubusercontent.com/10873132/65697727-6ac46100-e049-11e9-8b30-81b3b4410bb0.png)

My application stops running when in --compatibility mode but runs fine with normal command without the --compatibility flag. Is there something I have to do in babelrc to get this to work?

**Comment by LarsDenBakker** [comment]
@lakshay35 this is a bit of an edge case. turning on compaitbility mode enables babel but doesn't read your custom babelrc. Because you're using syntax which babel doesn't support out of the box, it gives an error. The solution here is to also pass the `babel` flag so that your custom `babelrc` read parsed as well.

**Comment by LarsDenBakker** [comment]
Closing this, using the `--babel` flag is the solution here.
