### ISSUE TITLE
[create] element and class definition should not be separated in all cases

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#932]
Separating the class definition and the call to `customElements.define` is inconvenient. It may make sense in some cases when building reusable components, but not when building components for own usage. I think we should not set this up when scaffolding an application.

**Comment by justinfagnani** [comment]
> It may make sense in some cases when building reusable components

I don't think it makes sense even in this case. Since there's a 1-1 relationship between tagname and class, you can't actually separate the definition for reusable components, because if one consumer registers the element with one name, other consumers will be prevented from registering with another name. The component in all practicality _must_ register itself.

If other consumers want to register with a different name, they can register a trivial subclass.

**Comment by LarsDenBakker** [comment]
That's true... but if a consumer wants to reuse just your class definition to subclass it it's better if they don't also get the custom element definition for free. 

I don't know how much of a use case it is though, I'm not particularly tied to this concept.

**Comment by Westbrook** [comment]
I'm pretty sure that THE use case for these not living together is when an application is already using an element defined at `my-element` and then wants to import a new element class called `MyElement` that is by default registered as `my-element` but wants to use it via a different name without, knowing that it isn't a dependency of other dependencies. This can be separately worked around via tree shaking of side effects, so it might not be an issue, however in a situation where you're running with no tools/build there is no way to approximate this end result of which I am currently aware.

**Comment by justinfagnani** [comment]
@Westbrook is the application going to subclass the element? Have you seen this in practice?

**Comment by Westbrook** [comment]
At the intersection of lack of discoverability (with the aging of webcomponents.org and the only early development of https://catalog.open-wc.org/) and me being pretty hardheadedly stubborn, I don't often afford myself the luxury of relying on third-party components, so no I've not seen this practice. However, there's a little Paul Kinlan whispering in my ear about beautiful open/layered web possibilities that may never actually come to pass: https://paul.kinlan.me/custom-elements-ecosystem/

In the case above the ability to subclass or not isn't really the question, it's not having the registration crash because the new element automatically stepped on the previously used element name. I agree that it's an edge case now, but it's hard to say the realities that bring that into being (an as yet smaller web component community and aggressive namespacing in larger-scale libraries) is something that we can rely on in the long term. Hopefully scoped registries come soon! However, for now, there is a sizable enough number of `cool-button` demos to hope that the problem gets worse (from an expanding community) before new API is able to be agreed on/implemented to make it better.

**Comment by LarsDenBakker** [comment]
After discussion we decided to keep it the way it is for the component generator, but remove the abstraction from the app generator.

The rationale for the component generator is that `index.js` should be side effect free, any side effects should be separate imports.

**Comment by odinho** [comment]
This was suprising to me btw.

Especially as you also don't mention it in i.e. https://open-wc.org/codelabs/intermediate/lit-html.html?index=/codelabs/#9 where you just "import" another component and use it.

I added the app starter and the component starter, and bound them together by an import, then wondering why I had to suddenly register it, whilst your docs was saying something else.

Having a default-export that does define/register the component, and using a `/path` if you want to use another name should work.

I think this will be hard to explain and it will make third-party components harder to just use since it won't be clear how you're supposed to use it.

**Comment by LarsDenBakker** [comment]
The problem here is that registering components is a side effect, one that can't be undone.

A package entrypoint should never contain any side effects, each side effect should be opt-in with a separate entrypoint. This is best for tree shaking and bundling, and generally for predictability. @daKmoR convinced me of this :)

For web components [scoped custom element registries](https://github.com/w3c/webcomponents/issues/716) will make this a more common best practice.

We're sticking to our current recommendations, I'll close this issue now.

**Comment by odinho** [comment]
Not so hot on the scoping either. But the guide should probably say something on the "material button" import, -- something like "// unlike open-wc, this component self-registers, so you don't need to customElements.define it", maybe.
