### ISSUE TITLE
[lit-helpers] spread directives

### ISSUE THREAD

**Issue by LarsDenBakker** [open-wc/open-wc#967]
We are thinking about adding some lit-html helpers for commonly requested functionality, starting with a spread directive.

Currently I'm thinking of this syntax:
```js
html`
  <my-element ...=${spreadBindings({ 'foo': 'bar', '.foo': 'bar', '@foo': 'bar', '?foo': 'bar' })}>
`
```

Where the keys aligns with the lit-html syntax of setting attributes, properties and event listeners.

Additionally because setting properties or attributes is the most common use case, I think we should add a helper for that:
```js
html`
  <my-element ...=${spreadProps({ 'foo': 'bar' })}>
  <my-element ...=${spreadAttributes({ 'foo': 'bar' })}>
`
```

We're looking to gather feedback on what people think of this, and if this is how they expect this to work.

See also the discussion on adding this to lit-html: https://github.com/Polymer/lit-html/issues/923

**Comment by bennypowers** [comment]
We discussed this on Slack and came to the following conclusions:

- we might have preferred something like
```js
html`<x-l 
    ...="${{ prop2: 1, prop2: 2 }}"
    ..$="${{ attr1: '1', attr2: '2' }}"
    ..?="${{ bool1: true, bool2: false }}"
    ..@="${{ click: this.onClick }}"
></x-l>`
```
But this would require upstream changes to `lit-html`, since an attribute directive doesn't have access to the attribute name. Therefore, we prefer to export specifically-named directives for props, attrs, listeners, etc. This also means that the attr name is of no consequence:
```js
html`
  <x-l atty-mc-attrface="${spreadProps({ foo, bar, baz })"></x-l>
`
```
