### ISSUE TITLE
Importing @open-wc/testing-helpers fails with window.chai not found

### ISSUE THREAD

**Issue by ErikGrimes** [open-wc/open-wc#989]
When using @openwc/testing in a Karma/Webpack/Storybook environment, importing testing-helpers fails as window.chai is undefined.  Tests where we import from chai work fine. Any thoughts?

**Comment by LarsDenBakker** [comment]
This is because we import chai, which is just a plain script which registers chai to the window. Unfortuantely, webpack turns it into a module so chai isn't there on the window anymore.

I remember we had discussed this before, but I'm not sure if we came to a solution. Do you remember @daKmoR ?

Perhaps this would work:

```js
import 'chai';
let chai = window.chai;
if (!chai) {
  chai = require('chai');
}
```
